import {
  Region,
  Province,
  City,
  Barangay,
  User,
  Facility,
  EnvironmentalReport,
  Event,
  Challenge,
  GarbageSchedule,
  UserActivityLog,
  Announcement,
  FeedPost,
  GovernmentPage,
  AppNotification,
  EcoProject,
  CommunityPoll,
  EnvironmentalAsset,
  EnvironmentalAlert,
  BulkWastePickupRequest,
  EcoBusiness,
  PartnerOrganization,
  FamilyGroup,
  TreeItem,
  PersonalCalendarEvent,
  BarangayImprovement
} from '../types';

export const INITIAL_REGIONS: Region[] = [
  { code: 'NCR', name: 'National Capital Region (NCR)' },
  { code: 'CAR', name: 'Cordillera Administrative Region (CAR)' },
  { code: 'R01', name: 'Region I - Ilocos Region' },
  { code: 'R02', name: 'Region II - Cagayan Valley' },
  { code: 'R03', name: 'Region III - Central Luzon' },
  { code: 'R04A', name: 'Region IV-A - CALABARZON' },
  { code: 'R04B', name: 'Region IV-B - MIMAROPA' },
  { code: 'R05', name: 'Region V - Bicol Region' },
  { code: 'R06', name: 'Region VI - Western Visayas' },
  { code: 'R07', name: 'Region VII - Central Visayas' },
  { code: 'R08', name: 'Region VIII - Eastern Visayas' },
  { code: 'R09', name: 'Region IX - Zamboanga Peninsula' },
  { code: 'R10', name: 'Region X - Northern Mindanao' },
  { code: 'R11', name: 'Region XI - Davao Region' },
  { code: 'R12', name: 'Region XII - SOCCSKSARGEN' },
  { code: 'R13', name: 'Region XIII - Caraga' },
  { code: 'BARMM', name: 'Bangsamoro Autonomous Region (BARMM)' },
];

export const INITIAL_PROVINCES: Province[] = [
  { code: 'MM', name: 'Metro Manila', regionCode: 'NCR' },
  { code: 'BGT', name: 'Benguet', regionCode: 'CAR' },
  { code: 'BUL', name: 'Bulacan', regionCode: 'R03' },
  { code: 'PAM', name: 'Pampanga', regionCode: 'R03' },
  { code: 'CAV', name: 'Cavite', regionCode: 'R04A' },
  { code: 'LAG', name: 'Laguna', regionCode: 'R04A' },
  { code: 'BAT', name: 'Batangas', regionCode: 'R04A' },
  { code: 'CEB', name: 'Cebu', regionCode: 'R07' },
  { code: 'ILO', name: 'Iloilo', regionCode: 'R06' },
  { code: 'DAV', name: 'Davao del Sur', regionCode: 'R11' },
];

export const INITIAL_CITIES: City[] = [
  // NCR
  { code: 'PASIG', name: 'Pasig City', provinceCode: 'MM', regionCode: 'NCR', isNCR: true },
  { code: 'MAKATI', name: 'Makati City', provinceCode: 'MM', regionCode: 'NCR', isNCR: true },
  { code: 'QC', name: 'Quezon City', provinceCode: 'MM', regionCode: 'NCR', isNCR: true },
  { code: 'MANILA', name: 'City of Manila', provinceCode: 'MM', regionCode: 'NCR', isNCR: true },
  { code: 'TAGUIG', name: 'Taguig City', provinceCode: 'MM', regionCode: 'NCR', isNCR: true },
  { code: 'MANDA', name: 'Mandaluyong City', provinceCode: 'MM', regionCode: 'NCR', isNCR: true },
  // CAR
  { code: 'BAGUIO', name: 'Baguio City', provinceCode: 'BGT', regionCode: 'CAR', isIndependent: true },
  // Cavite
  { code: 'DASMA', name: 'Dasmariñas City', provinceCode: 'CAV', regionCode: 'R04A' },
  // Cebu
  { code: 'CEBUC', name: 'Cebu City', provinceCode: 'CEB', regionCode: 'R07', isIndependent: true },
  // Davao
  { code: 'DAVAOC', name: 'Davao City', provinceCode: 'DAV', regionCode: 'R11', isIndependent: true },
];

export const INITIAL_BARANGAYS: Barangay[] = [
  // Pasig City
  {
    id: 'brgy-kapitolyo',
    psgcCode: '137403011',
    name: 'Kapitolyo',
    cityCode: 'PASIG',
    cityName: 'Pasig City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.5714,
    lng: 121.0617,
    population: 18500,
    totalUsers: 1240,
    score: {
      wasteManagement: 23,
      recycling: 18,
      communityParticipation: 18,
      reportsResolution: 14,
      cleanupActivities: 9,
      sustainabilityChallenges: 4,
      educationParticipation: 4,
      totalScore: 90,
      tier: 'Platinum',
    },
    totalRecycledKg: 18700,
    totalReportsResolved: 128,
    totalReportsReceived: 135,
    mrfActive: true,
    garbageScheduleDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
  },
  {
    id: 'brgy-san-antonio-pasig',
    psgcCode: '137403022',
    name: 'San Antonio',
    cityCode: 'PASIG',
    cityName: 'Pasig City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.5826,
    lng: 121.0658,
    population: 21300,
    totalUsers: 890,
    score: {
      wasteManagement: 21,
      recycling: 17,
      communityParticipation: 16,
      reportsResolution: 13,
      cleanupActivities: 8,
      sustainabilityChallenges: 4,
      educationParticipation: 3,
      totalScore: 82,
      tier: 'Gold',
    },
    totalRecycledKg: 14500,
    totalReportsResolved: 94,
    totalReportsReceived: 105,
    mrfActive: true,
    garbageScheduleDays: ['Tuesday', 'Thursday', 'Saturday'],
  },
  {
    id: 'brgy-oranbo',
    psgcCode: '137403018',
    name: 'Oranbo',
    cityCode: 'PASIG',
    cityName: 'Pasig City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.5768,
    lng: 121.0632,
    population: 8900,
    totalUsers: 450,
    score: {
      wasteManagement: 19,
      recycling: 15,
      communityParticipation: 15,
      reportsResolution: 11,
      cleanupActivities: 7,
      sustainabilityChallenges: 3,
      educationParticipation: 3,
      totalScore: 73,
      tier: 'Silver',
    },
    totalRecycledKg: 6200,
    totalReportsResolved: 45,
    totalReportsReceived: 58,
    mrfActive: false,
    garbageScheduleDays: ['Monday', 'Thursday'],
  },
  {
    id: 'brgy-ugong-pasig',
    psgcCode: '137403030',
    name: 'Ugong',
    cityCode: 'PASIG',
    cityName: 'Pasig City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.5898,
    lng: 121.0776,
    population: 26400,
    totalUsers: 1120,
    score: {
      wasteManagement: 22,
      recycling: 18,
      communityParticipation: 17,
      reportsResolution: 13,
      cleanupActivities: 8,
      sustainabilityChallenges: 4,
      educationParticipation: 4,
      totalScore: 86,
      tier: 'Gold',
    },
    totalRecycledKg: 16800,
    totalReportsResolved: 110,
    totalReportsReceived: 122,
    mrfActive: true,
    garbageScheduleDays: ['Monday', 'Wednesday', 'Friday'],
  },
  // Makati City
  {
    id: 'brgy-san-lorenzo-makati',
    psgcCode: '137602025',
    name: 'San Lorenzo',
    cityCode: 'MAKATI',
    cityName: 'Makati City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.5512,
    lng: 121.0189,
    population: 13200,
    totalUsers: 1280,
    score: {
      wasteManagement: 24,
      recycling: 19,
      communityParticipation: 19,
      reportsResolution: 15,
      cleanupActivities: 9,
      sustainabilityChallenges: 5,
      educationParticipation: 4,
      totalScore: 95,
      tier: 'Platinum',
    },
    totalRecycledKg: 22400,
    totalReportsResolved: 142,
    totalReportsReceived: 145,
    mrfActive: true,
    garbageScheduleDays: ['Daily Morning Collection'],
  },
  {
    id: 'brgy-bel-air',
    psgcCode: '137602003',
    name: 'Bel-Air',
    cityCode: 'MAKATI',
    cityName: 'Makati City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.5604,
    lng: 121.0281,
    population: 18200,
    totalUsers: 950,
    score: {
      wasteManagement: 23,
      recycling: 18,
      communityParticipation: 17,
      reportsResolution: 14,
      cleanupActivities: 8,
      sustainabilityChallenges: 4,
      educationParticipation: 4,
      totalScore: 88,
      tier: 'Gold',
    },
    totalRecycledKg: 15900,
    totalReportsResolved: 88,
    totalReportsReceived: 92,
    mrfActive: true,
    garbageScheduleDays: ['Monday', 'Wednesday', 'Friday', 'Sunday'],
  },
  {
    id: 'brgy-poblacion-makati',
    psgcCode: '137602021',
    name: 'Poblacion',
    cityCode: 'MAKATI',
    cityName: 'Makati City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.5678,
    lng: 121.0312,
    population: 21100,
    totalUsers: 780,
    score: {
      wasteManagement: 18,
      recycling: 14,
      communityParticipation: 15,
      reportsResolution: 11,
      cleanupActivities: 6,
      sustainabilityChallenges: 3,
      educationParticipation: 3,
      totalScore: 70,
      tier: 'Silver',
    },
    totalRecycledKg: 8900,
    totalReportsResolved: 62,
    totalReportsReceived: 82,
    mrfActive: true,
    garbageScheduleDays: ['Tuesday', 'Thursday', 'Saturday'],
  },
  // Quezon City
  {
    id: 'brgy-batasan-hills',
    psgcCode: '137404006',
    name: 'Batasan Hills',
    cityCode: 'QC',
    cityName: 'Quezon City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.6854,
    lng: 121.0924,
    population: 161000,
    totalUsers: 2450,
    score: {
      wasteManagement: 17,
      recycling: 13,
      communityParticipation: 14,
      reportsResolution: 10,
      cleanupActivities: 6,
      sustainabilityChallenges: 2,
      educationParticipation: 3,
      totalScore: 65,
      tier: 'Bronze',
    },
    totalRecycledKg: 19800,
    totalReportsResolved: 154,
    totalReportsReceived: 210,
    mrfActive: true,
    garbageScheduleDays: ['Monday', 'Wednesday', 'Friday'],
  },
  {
    id: 'brgy-loyola-heights',
    psgcCode: '137404052',
    name: 'Loyola Heights',
    cityCode: 'QC',
    cityName: 'Quezon City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.6402,
    lng: 121.0721,
    population: 22400,
    totalUsers: 1420,
    score: {
      wasteManagement: 23,
      recycling: 18,
      communityParticipation: 18,
      reportsResolution: 14,
      cleanupActivities: 9,
      sustainabilityChallenges: 4,
      educationParticipation: 5,
      totalScore: 91,
      tier: 'Platinum',
    },
    totalRecycledKg: 21000,
    totalReportsResolved: 98,
    totalReportsReceived: 102,
    mrfActive: true,
    garbageScheduleDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
  },
  // Manila City
  {
    id: 'brgy-sampaloc-zone-41',
    psgcCode: '133900001',
    name: 'Barangay 411 (Sampaloc)',
    cityCode: 'MANILA',
    cityName: 'City of Manila',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.6082,
    lng: 120.9942,
    population: 12800,
    totalUsers: 540,
    score: {
      wasteManagement: 15,
      recycling: 11,
      communityParticipation: 12,
      reportsResolution: 8,
      cleanupActivities: 5,
      sustainabilityChallenges: 2,
      educationParticipation: 2,
      totalScore: 55,
      tier: 'Developing',
    },
    totalRecycledKg: 4200,
    totalReportsResolved: 32,
    totalReportsReceived: 56,
    mrfActive: false,
    garbageScheduleDays: ['Tuesday', 'Thursday', 'Saturday'],
  },
  // Taguig City
  {
    id: 'brgy-fort-bonifacio',
    psgcCode: '137607008',
    name: 'Fort Bonifacio (BGC)',
    cityCode: 'TAGUIG',
    cityName: 'Taguig City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.5519,
    lng: 121.0494,
    population: 28900,
    totalUsers: 1890,
    score: {
      wasteManagement: 24,
      recycling: 19,
      communityParticipation: 18,
      reportsResolution: 14,
      cleanupActivities: 8,
      sustainabilityChallenges: 5,
      educationParticipation: 4,
      totalScore: 92,
      tier: 'Platinum',
    },
    totalRecycledKg: 28500,
    totalReportsResolved: 165,
    totalReportsReceived: 170,
    mrfActive: true,
    garbageScheduleDays: ['Daily Evening Collection'],
  },
  // Cebu City
  {
    id: 'brgy-lahug-cebu',
    psgcCode: '072217032',
    name: 'Lahug',
    cityCode: 'CEBUC',
    cityName: 'Cebu City',
    provinceCode: 'CEB',
    provinceName: 'Cebu',
    regionCode: 'R07',
    regionName: 'Region VII - Central Visayas',
    lat: 10.3341,
    lng: 123.8964,
    population: 38200,
    totalUsers: 840,
    score: {
      wasteManagement: 20,
      recycling: 16,
      communityParticipation: 16,
      reportsResolution: 12,
      cleanupActivities: 7,
      sustainabilityChallenges: 3,
      educationParticipation: 4,
      totalScore: 78,
      tier: 'Gold',
    },
    totalRecycledKg: 11200,
    totalReportsResolved: 72,
    totalReportsReceived: 88,
    mrfActive: true,
    garbageScheduleDays: ['Monday', 'Wednesday', 'Friday'],
  },
  // Davao City
  {
    id: 'brgy-poblacion-davao',
    psgcCode: '112402001',
    name: 'Poblacion District',
    cityCode: 'DAVAOC',
    cityName: 'Davao City',
    provinceCode: 'DAV',
    provinceName: 'Davao del Sur',
    regionCode: 'R11',
    regionName: 'Region XI - Davao Region',
    lat: 7.0731,
    lng: 125.6128,
    population: 45000,
    totalUsers: 1150,
    score: {
      wasteManagement: 22,
      recycling: 17,
      communityParticipation: 17,
      reportsResolution: 13,
      cleanupActivities: 8,
      sustainabilityChallenges: 4,
      educationParticipation: 4,
      totalScore: 85,
      tier: 'Gold',
    },
    totalRecycledKg: 15400,
    totalReportsResolved: 95,
    totalReportsReceived: 108,
    mrfActive: true,
    garbageScheduleDays: ['Tuesday', 'Thursday', 'Saturday'],
  },
  // Baguio City
  {
    id: 'brgy-burnham-baguio',
    psgcCode: '141102010',
    name: 'Burnham - Legarda',
    cityCode: 'BAGUIO',
    cityName: 'Baguio City',
    provinceCode: 'BGT',
    provinceName: 'Benguet',
    regionCode: 'CAR',
    regionName: 'CAR',
    lat: 16.4111,
    lng: 120.5955,
    population: 14200,
    totalUsers: 620,
    score: {
      wasteManagement: 21,
      recycling: 16,
      communityParticipation: 16,
      reportsResolution: 12,
      cleanupActivities: 8,
      sustainabilityChallenges: 3,
      educationParticipation: 3,
      totalScore: 79,
      tier: 'Silver',
    },
    totalRecycledKg: 9800,
    totalReportsResolved: 58,
    totalReportsReceived: 66,
    mrfActive: true,
    garbageScheduleDays: ['Monday', 'Wednesday', 'Friday'],
  },
];

export const INITIAL_GOVERNMENT_PAGES: GovernmentPage[] = [
  {
    id: 'gov-denr',
    name: 'Department of Environment and Natural Resources',
    acronym: 'DENR Central',
    category: 'National Agency',
    description: 'Official national executive department responsible for governing, conserving, and protecting the Philippines\' natural resources and environment under RA 9003.',
    avatarUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=200',
    coverUrl: 'https://images.unsplash.com/photo-1511497584788-876761c11969?auto=format&fit=crop&q=80&w=800',
    verified: true,
    followersCount: 14250,
    website: 'https://denr.gov.ph',
  },
  {
    id: 'gov-mmda',
    name: 'MMDA Solid Waste Management Office',
    acronym: 'MMDA',
    category: 'LGU Office',
    description: 'Metropolitan Manila Development Authority supervising waste management, flood control, and environmental sanitation across 17 LGUs in NCR.',
    avatarUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80&w=200',
    verified: true,
    followersCount: 9800,
    regionCode: 'NCR',
    website: 'https://mmda.gov.ph',
  },
  {
    id: 'gov-pasig-cenro',
    name: 'Pasig City Environment & Natural Resources Office',
    acronym: 'Pasig CENRO',
    category: 'LGU Office',
    description: 'Lead environmental agency of Pasig City driving urban greening, MRF operations, river cleanup, and zero-waste household segregation.',
    avatarUrl: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&q=80&w=200',
    verified: true,
    followersCount: 6540,
    regionCode: 'NCR',
    cityCode: 'PASIG',
    cityName: 'Pasig City',
  },
  {
    id: 'gov-brgy-kapitolyo',
    name: 'Barangay Kapitolyo Official Govt Page',
    acronym: 'Brgy Kapitolyo Council',
    category: 'Barangay Office',
    description: 'Official local government page of Brgy. Kapitolyo, Pasig City. Providing waste collection schedules, MRF updates, and community cleanup drives.',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    verified: true,
    followersCount: 3820,
    regionCode: 'NCR',
    cityCode: 'PASIG',
    cityName: 'Pasig City',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
  },
  {
    id: 'gov-ccc',
    name: 'Climate Change Commission Philippines',
    acronym: 'CCC PH',
    category: 'National Agency',
    description: 'Lead policy-making body of the government tasked to coordinate, monitor and evaluate climate change programs and sustainable barangay action plans.',
    avatarUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=200',
    verified: true,
    followersCount: 11200,
  },
  {
    id: 'gov-cebu-cenro',
    name: 'Cebu City Environment & Natural Resources Office',
    acronym: 'Cebu CCENRO',
    category: 'LGU Office',
    description: 'Promoting clean waterways, zero single-use plastic mandates, and coastal resource conservation across Cebu City barangays.',
    avatarUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=200',
    verified: true,
    followersCount: 5200,
    regionCode: 'R07',
    cityCode: 'CEBUC',
    cityName: 'Cebu City',
  },
];

export const INITIAL_USERS: User[] = [];

export const INITIAL_FACILITIES: Facility[] = [
  {
    id: 'fac-1',
    name: 'Kapitolyo Eco-Recovery & MRF Center',
    category: 'mrf',
    address: 'East Capitol Drive, Brgy. Kapitolyo',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    city: 'Pasig City',
    province: 'Metro Manila',
    lat: 14.5721,
    lng: 121.0625,
    acceptedMaterials: ['Plastic', 'Paper', 'Glass', 'Cardboard', 'Organics'],
    openingHours: '8:00 AM - 5:00 PM (Mon-Sat)',
    contact: '(02) 8631-1122',
    description: 'Official Materials Recovery Facility of Brgy. Kapitolyo. Provides eco-points exchange for clean dry plastic recyclables.',
  },
  {
    id: 'fac-2',
    name: 'San Antonio Junk Shop & Recycling Hub',
    category: 'junkshop',
    address: 'Shaw Blvd cor. San Antonio St.',
    barangayId: 'brgy-san-antonio-pasig',
    barangayName: 'San Antonio',
    city: 'Pasig City',
    province: 'Metro Manila',
    lat: 14.5815,
    lng: 121.0642,
    acceptedMaterials: ['Scrap Metal', 'Copper', 'Aluminum Cans', 'PET Bottles', 'Paper'],
    openingHours: '7:30 AM - 6:00 PM Daily',
    contact: '0920-444-1234',
    description: 'Community-accredited junk shop purchasing household scrap metals, batteries, and bulk plastics at fair daily market rates.',
  },
  {
    id: 'fac-3',
    name: 'Ortigas E-Waste Drop-off Hub',
    category: 'ewaste',
    address: 'F. Ortigas Jr. Road, Ortigas Center',
    barangayId: 'brgy-san-antonio-pasig',
    barangayName: 'San Antonio',
    city: 'Pasig City',
    province: 'Metro Manila',
    lat: 14.5842,
    lng: 121.0601,
    acceptedMaterials: ['Old Laptops', 'Cellphones', 'Batteries', 'Chargers', 'Circuit Boards'],
    openingHours: '9:00 AM - 7:00 PM (Mon-Fri)',
    contact: '(02) 8687-9900',
    description: 'Safe electronic waste drop-off station ensuring hazardous components are diverted from landfills and recycled responsibly.',
  },
  {
    id: 'fac-4',
    name: 'Pasig Central Organic Composting Park',
    category: 'composting',
    address: 'Caruncho Ave, Brgy. San Nicolas',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    city: 'Pasig City',
    province: 'Metro Manila',
    lat: 14.5605,
    lng: 121.0805,
    acceptedMaterials: ['Fruit Scraps', 'Vegetable Waste', 'Dry Leaves', 'Coffee Grounds'],
    openingHours: '6:00 AM - 4:00 PM (Daily)',
    contact: '(02) 8643-0000',
    description: 'Community vermi-composting facility converting kitchen food waste into rich organic fertilizer for barangay urban gardens.',
  },
  {
    id: 'fac-5',
    name: 'San Lorenzo Eco-Hub & Bottle Bank',
    category: 'recycling',
    address: 'Amorsolo St, Brgy. San Lorenzo',
    barangayId: 'brgy-san-lorenzo-makati',
    barangayName: 'San Lorenzo',
    city: 'Makati City',
    province: 'Metro Manila',
    lat: 14.5501,
    lng: 121.0175,
    acceptedMaterials: ['Glass Bottles', 'PET Containers', 'Tetra Pak', 'Aluminum'],
    openingHours: '8:00 AM - 6:00 PM (Mon-Sat)',
    contact: '(02) 8812-3456',
    description: 'Award-winning recycling drop-off depot with digital weight scales and instant app Eco Points credit.',
  },
  {
    id: 'fac-6',
    name: 'Batasan Green Community MRF',
    category: 'mrf',
    address: 'Batasan-San Mateo Road, QC',
    barangayId: 'brgy-batasan-hills',
    barangayName: 'Batasan Hills',
    city: 'Quezon City',
    province: 'Metro Manila',
    lat: 14.6882,
    lng: 121.0945,
    acceptedMaterials: ['Plastic', 'Paper', 'Glass', 'Cardboard', 'Metal'],
    openingHours: '7:00 AM - 5:00 PM (Mon-Fri)',
    contact: '(02) 8931-5000',
    description: 'Large-capacity sorting facility serving Batasan Hills residents and local market vendors.',
  },
];

export const INITIAL_REPORTS: EnvironmentalReport[] = [
  {
    id: 'rep-1',
    category: 'Illegal Dumping',
    description: 'Large pile of mixed unsegregated household waste and construction debris dumped near the vacant lot along West Capitol Drive. Violating RA 9003 Section 48 prohibition against open dumping.',
    locationAddress: 'West Capitol Drive cor. Stella Maris St.',
    landmark: 'Behind vacant commercial lot near corner bakery',
    tags: ['#IllegalDumping', '#PlasticWaste', '#HealthHazard', '#UrgentSanitation'],
    urgency: 'High',
    estimatedVolume: 'Medium (Pickup load)',
    lat: 14.5732,
    lng: 121.0615,
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    reporterId: 'user-sample-1',
    reporterName: 'Maria Santos',
    photoUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&q=80&w=600',
    status: 'In Progress',
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    officialNotes: 'Brgy. Kapitolyo Clean & Green Task Force dispatched dump truck for 2:00 PM clearing operation. Warning notice posted.',
    upvotesCount: 8,
    upvotedUserIds: ['user-1', 'user-2'],
  },
  {
    id: 'rep-2',
    category: 'Clogged Drainage',
    description: 'Accumulation of single-use plastic bottles, styrofoam cups, and silt clogging the roadside drainage culvert. Water is starting to stagnate and flood during afternoon rains.',
    locationAddress: 'East Capitol Drive near Sta. Monica Bridge',
    landmark: 'In front of Kapitolyo High School drainage inlet',
    tags: ['#BlockedCanal', '#StagnantWater', '#PlasticPollution', '#NearSchool'],
    urgency: 'Critical',
    estimatedVolume: 'Small (1-2 bags)',
    lat: 14.5718,
    lng: 121.0645,
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    reporterId: 'user-sample-2',
    reporterName: 'Juan Dela Cruz',
    photoUrl: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&q=80&w=600',
    status: 'Pending',
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    upvotesCount: 14,
    upvotedUserIds: ['user-1', 'user-3', 'user-4'],
  },
  {
    id: 'rep-3',
    category: 'Overflowing Bin',
    description: 'Public segregation bins outside the market are overflowing with uncollected food containers and plastic bags. Strays are scattering garbage onto the pedestrian sidewalk.',
    locationAddress: 'San Antonio Public Market Perimeter',
    landmark: 'Beside North Gate jeepney terminal',
    tags: ['#OverflowingBin', '#CommercialViolation', '#OdorNuisance', '#PlasticWaste'],
    urgency: 'Medium',
    estimatedVolume: 'Medium (Pickup load)',
    lat: 14.5822,
    lng: 121.0638,
    barangayId: 'brgy-san-antonio-pasig',
    barangayName: 'San Antonio',
    cityName: 'Pasig City',
    reporterId: 'user-sample-3',
    reporterName: 'Elena Ramos',
    photoUrl: 'https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?auto=format&fit=crop&q=80&w=600',
    status: 'Resolved',
    createdAt: new Date(Date.now() - 48 * 3600000).toISOString(),
    resolvedAt: new Date(Date.now() - 20 * 3600000).toISOString(),
    officialNotes: 'Solid Waste Team emptied all bins, disinfected the perimeter, and installed secondary recycling cages.',
    officialAction: 'Sanitation team emptied bins and scheduled twice-daily collections for the market zone.',
    upvotesCount: 19,
    upvotedUserIds: [],
  },
  {
    id: 'rep-4',
    category: 'Open Burning (Siga)',
    description: 'Open burning of yard waste, dried palm fronds, and plastic packaging observed in the backyard lot. Heavy smoke entering neighboring residences violating Clean Air Act and RA 9003.',
    locationAddress: 'Purok 4, San Lorenzo Village Boundary',
    landmark: 'Behind old storage shed near perimeter wall',
    tags: ['#OpenBurning', '#HealthHazard', '#AirPollution', '#ResidentialZone'],
    urgency: 'High',
    estimatedVolume: 'Small (1-2 bags)',
    lat: 14.5525,
    lng: 121.0195,
    barangayId: 'brgy-san-lorenzo-makati',
    barangayName: 'San Lorenzo',
    cityName: 'Makati City',
    reporterId: 'user-sample-4',
    reporterName: 'Carlos Mendoza',
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=600',
    status: 'Resolved',
    createdAt: new Date(Date.now() - 36 * 3600000).toISOString(),
    resolvedAt: new Date(Date.now() - 10 * 3600000).toISOString(),
    officialNotes: 'Barangay Tanod responded immediately, extinguished the burn, and issued formal citation for illegal burning under Barangay Ordinance.',
    upvotesCount: 6,
    upvotedUserIds: [],
  }
];

export const INITIAL_EVENTS: Event[] = [
  {
    id: 'evt-1',
    title: 'Weekend Marikina Riverbanks Cleanup Drive',
    description: 'Join neighbors in collecting floating plastics, riverbank litter, and planting vetiver grass along the waterway.',
    date: '2026-08-15',
    time: '06:30 AM - 09:30 AM',
    location: 'Marikina River Park Promenade (Kapitolyo Boundary)',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    organizerName: 'Barangay Kapitolyo Environmental Committee',
    category: 'Cleanup',
    pointsAwarded: 150,
    registeredUserIds: [],
    maxParticipants: 60,
    lat: 14.5742,
    lng: 121.0665,
  },
  {
    id: 'evt-2',
    title: 'Household Vermi-Composting Workshop & Free Starter Kit',
    description: 'Learn how to turn kitchen food scraps into nutrient-rich garden soil using African Nightcrawler worms.',
    date: '2026-08-22',
    time: '02:00 PM - 04:30 PM',
    location: 'San Antonio Community Covered Court',
    barangayId: 'brgy-san-antonio-pasig',
    barangayName: 'San Antonio',
    organizerName: 'LGU Pasig City Clean & Green Team',
    category: 'Workshop',
    pointsAwarded: 100,
    registeredUserIds: [],
    maxParticipants: 40,
    lat: 14.5831,
    lng: 121.0660,
  },
  {
    id: 'evt-3',
    title: 'Trash to Cash Electronic & Plastic Exchange',
    description: 'Bring old appliances, glass, plastic bottles, and paper in exchange for eco points, sacks of rice, or groceries.',
    date: '2026-08-29',
    time: '08:00 AM - 12:00 PM',
    location: 'Kapitolyo Multi-Purpose Center Grounds',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    organizerName: 'EcoBarangay Alliance & Pasig LGU',
    category: 'Recycling Drive',
    pointsAwarded: 120,
    registeredUserIds: [],
    maxParticipants: 150,
    lat: 14.5718,
    lng: 121.0612,
  },
];

export const INITIAL_CHALLENGES: Challenge[] = [
  {
    id: 'chl-1',
    title: '7-Day Zero Single-Use Plastic Week',
    description: 'Avoid single-use plastic water bottles, plastic straws, and plastic shopping bags for 7 consecutive days.',
    category: 'Waste Reduction',
    durationDays: 7,
    pointsAwarded: 200,
    icon: 'no_drinks',
    joinedUserIds: [],
    completedUserIds: [],
  },
  {
    id: 'chl-2',
    title: 'Segregate 10kg Recyclables Challenge',
    description: 'Separate PET bottles, clean cardboard, and metal cans at home and drop them off at your nearest MRF.',
    category: 'Recycling',
    durationDays: 14,
    pointsAwarded: 250,
    icon: 'recycling',
    joinedUserIds: [],
    completedUserIds: [],
  },
  {
    id: 'chl-3',
    title: 'Community Environmental Champion',
    description: 'Report 3 environmental problems or illegal dumping sites in your neighborhood to help LGU cleanups.',
    category: 'Reporting & Civic Duty',
    durationDays: 30,
    pointsAwarded: 300,
    icon: 'campaign',
    joinedUserIds: [],
    completedUserIds: [],
  },
  {
    id: 'chl-4',
    title: 'Kitchen Scraps Composting Pioneer',
    description: 'Divert 5kg of kitchen food scraps to a backyard pit, vermi bin, or community composting facility.',
    category: 'Composting',
    durationDays: 10,
    pointsAwarded: 180,
    icon: 'eco',
    joinedUserIds: [],
    completedUserIds: [],
  },
];

export const INITIAL_SCHEDULES: GarbageSchedule[] = [
  {
    id: 'sch-1',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    dayOfWeek: 'Monday & Thursday',
    timeSlot: '06:00 AM - 09:00 AM',
    wasteType: 'Biodegradable',
    instructions: 'Place food waste, garden trimmings, and organic material in green bags or covered bins outside gate.',
    truckNo: 'Truck #04 (Pasig Solid Waste)',
  },
  {
    id: 'sch-2',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    dayOfWeek: 'Tuesday & Friday',
    timeSlot: '06:00 AM - 09:00 AM',
    wasteType: 'Non-Biodegradable',
    instructions: 'Residual non-recyclable household waste tied securely in black plastic bags.',
    truckNo: 'Truck #08 (Pasig Solid Waste)',
  },
  {
    id: 'sch-3',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    dayOfWeek: 'Saturday',
    timeSlot: '08:00 AM - 12:00 PM',
    wasteType: 'Recyclable',
    instructions: 'Cleaned plastics, bottles, cardboard boxes, and tin cans tied or boxed separately for MRF pickup.',
    truckNo: 'Eco-Recycling Truck #01',
  },
  {
    id: 'sch-4',
    barangayId: 'brgy-san-antonio-pasig',
    barangayName: 'San Antonio',
    dayOfWeek: 'Monday, Wednesday, Friday',
    timeSlot: '07:00 AM - 10:00 AM',
    wasteType: 'Biodegradable',
    instructions: 'Must be segregated in labeled containers. Wet waste will not be collected if mixed with plastic.',
    truckNo: 'Truck #12',
  },
];

export const INITIAL_ACTIVITY_LOGS: UserActivityLog[] = [];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'anc-1',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    authorName: 'Barangay Kapitolyo Council',
    title: 'Strict Implementation of RA 9003 Waste Segregation',
    content: 'Starting this month, unsegregated trash will NOT be collected. Please ensure separate bins for Biodegradable (Nabubulok), Non-Biodegradable (Di-Nabubulok), and Recyclable items.',
    category: 'Urgent',
    createdAt: '2026-08-08T08:00:00Z',
  },
];

export const INITIAL_FEED_POSTS: FeedPost[] = [
  {
    id: 'post-gov-1',
    authorId: 'gov-denr',
    authorName: 'Department of Environment and Natural Resources',
    authorAvatar: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=200',
    authorRole: 'SYSTEM_ADMIN',
    governmentPageId: 'gov-denr',
    isGovernmentPost: true,
    barangayId: 'national',
    barangayName: 'National (DENR)',
    regionCode: 'NCR',
    content: '🏛️ DENR Official Notice: Pursuant to Republic Act 9003 (Ecological Solid Waste Management Act), all LGUs and Barangays nationwide are advised to maintain active Material Recovery Facilities (MRFs) and submit monthly waste diversion metrics. Let us build green, sustainable communities together! 🇵🇭',
    photoUrl: 'https://images.unsplash.com/photo-1511497584788-876761c11969?auto=format&fit=crop&q=80&w=800',
    likes: [],
    comments: [],
    sharesCount: 14,
    createdAt: '2026-08-09T08:00:00Z',
  },
  {
    id: 'post-gov-2',
    authorId: 'gov-pasig-cenro',
    authorName: 'Pasig City Environment & Natural Resources Office',
    authorAvatar: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&q=80&w=200',
    authorRole: 'BARANGAY_OFFICIAL',
    governmentPageId: 'gov-pasig-cenro',
    isGovernmentPost: true,
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    regionCode: 'NCR',
    provinceCode: 'MM',
    cityCode: 'PASIG',
    cityName: 'Pasig City',
    content: '🌱 Pasig City CENRO Bulletin: All registered households turning in recyclable plastics at any local MRF drop-off location can now log their waste and earn Eco Points. Check out your nearest barangay hub on the Eco-Map!',
    photoUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=800',
    likes: [],
    comments: [],
    sharesCount: 8,
    createdAt: '2026-08-08T15:20:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-sched-1',
    type: 'SCHEDULE',
    title: '🚛 Garbage Collection Alert: Biodegradable Waste',
    message: 'Pickup scheduled for tomorrow at 06:00 AM - 09:00 AM in Brgy. Kapitolyo. Please prepare kitchen scraps, food waste, and leaves in green/covered bins.',
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    read: false,
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    targetTab: 'schedule',
  },
  {
    id: 'notif-ann-1',
    type: 'ANNOUNCEMENT',
    title: '📢 Environmental Advisory: Strict RA 9003 Waste Segregation',
    message: 'Barangay Kapitolyo Council Notice: Mixed unsegregated garbage will strictly NOT be picked up by collection trucks. Ensure separate sorting at source.',
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    read: false,
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    targetTab: 'feed',
  },
  {
    id: 'notif-sched-2',
    type: 'SCHEDULE',
    title: '♻️ Weekend Recyclable & MRF Truck Collection',
    message: 'Saturday 08:00 AM - 12:00 PM: Dedicated Eco-Truck will collect cleaned PET plastic bottles, cartons, tin cans, and glass containers.',
    timestamp: new Date(Date.now() - 5 * 3600000).toISOString(),
    read: false,
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    targetTab: 'schedule',
  },
  {
    id: 'notif-alert-1',
    type: 'ALERT',
    title: '⚠️ Heavy Rainfall Advisory & Drainage Flood Watch',
    message: 'PAGASA Monsoon Warning: Residents along low-lying zones are advised to secure waste bins and keep canal gratings clear of plastic debris.',
    timestamp: new Date(Date.now() - 9 * 3600000).toISOString(),
    read: true,
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    targetTab: 'feed',
  },
  {
    id: 'notif-event-1',
    type: 'EVENT_SIGNUP',
    title: '🌱 Pasig River & Creek Clean-Up Drive',
    message: 'New community bayanihan cleanup scheduled for this Saturday 06:30 AM. Join fellow neighbors and earn +150 Eco Points!',
    timestamp: new Date(Date.now() - 16 * 3600000).toISOString(),
    read: true,
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    targetTab: 'events',
  },
  {
    id: 'notif-rep-1',
    type: 'REPORT_UPDATE',
    title: '✅ Citizen Report Resolved: West Capitol Drive',
    message: 'Barangay Clean & Green Task Force successfully cleared the reported illegal dumping site along West Capitol Drive.',
    timestamp: new Date(Date.now() - 24 * 3600000).toISOString(),
    read: true,
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    targetTab: 'reports',
  },
  {
    id: 'notif-rank-1',
    type: 'RANKING_CHANGE',
    title: '🏆 Barangay Ranking Update: Rank #12 in NCR',
    message: 'Brgy. Kapitolyo climbed to Rank #12 nationally with a 90.0 cleanliness and waste diversion score!',
    timestamp: new Date(Date.now() - 36 * 3600000).toISOString(),
    read: true,
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    targetTab: 'rankings',
  },
];

// ==================== NEW FEATURES INITIAL DATA ====================

export const INITIAL_PROJECTS: EcoProject[] = [
  {
    id: 'proj-1',
    title: 'Community Smart Recycling Hub',
    description: 'Establish a central automated sorting station with separate digital bins for plastics, paper, glass, and electronic waste.',
    category: 'Recycling Station',
    status: 'In Progress',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    suggestedByUserId: 'official',
    suggestedByName: 'Barangay Kapitolyo Council',
    votesCount: 42,
    votedUserIds: [],
    followersCount: 18,
    followedUserIds: [],
    progressPercent: 75,
    targetCompletionDate: '2026-09-01',
    beforePhotoUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&q=80&w=800',
    afterPhotoUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80&w=800',
    lat: 14.5720,
    lng: 121.0625,
    updates: [
      {
        id: 'upd-1',
        date: '2026-08-01',
        title: 'Concrete Base & Canopy Installed',
        description: 'Completed structural framework and rainproof roofing for sorting bins.',
        progressPercent: 75,
        photoUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80&w=800',
        authorName: 'Barangay Council',
      },
    ],
    feedback: [],
    createdAt: '2026-07-10T08:00:00Z',
  },
  {
    id: 'proj-2',
    title: 'Kapitolyo Organic Composting Facility',
    description: 'Transform market waste and household food scraps into nutrient-rich organic fertilizer for urban gardens.',
    category: 'Composting Facility',
    status: 'Approved',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    suggestedByUserId: 'official',
    suggestedByName: 'Barangay Environmental Committee',
    votesCount: 28,
    votedUserIds: [],
    followersCount: 12,
    followedUserIds: [],
    progressPercent: 30,
    targetCompletionDate: '2026-10-15',
    beforePhotoUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=800',
    lat: 14.5710,
    lng: 121.0605,
    updates: [],
    feedback: [],
    createdAt: '2026-07-20T09:30:00Z',
  },
];

export const INITIAL_POLLS: CommunityPoll[] = [
  {
    id: 'poll-1',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    title: 'What environmental project should Brgy. Kapitolyo prioritize for Q4 2026?',
    description: 'Vote to decide which sustainability project will receive primary barangay allocation.',
    options: [
      { id: 'opt-1', text: 'More Smart Recycling Bins', votesCount: 24 },
      { id: 'opt-2', text: 'Creek Drainage Cleanout & Trash Traps', votesCount: 18 },
      { id: 'opt-3', text: 'Urban Tree Planting in Park Areas', votesCount: 15 },
      { id: 'opt-4', text: 'Community Composting Facility', votesCount: 12 },
      { id: 'opt-5', text: 'Monthly E-Waste Collection Drive', votesCount: 9 },
    ],
    votedUserIds: [],
    totalVotes: 78,
    deadline: '2026-08-30',
    status: 'Active',
    createdAt: '2026-08-01T08:00:00Z',
    createdByOfficialName: 'Barangay Kapitolyo Council',
  },
];

export const INITIAL_ASSETS: EnvironmentalAsset[] = [
  {
    id: 'ast-1',
    name: 'Kapitolyo Centenary Banaba Tree',
    category: 'Trees',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    lat: 14.5718,
    lng: 121.0620,
    description: 'Heritage shade tree providing natural cooling and bird sanctuary.',
    condition: 'Healthy',
    details: 'Planted 1985. Species: Lagerstroemia speciosa',
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'ast-2',
    name: 'Kapitolyo Urban Community Garden',
    category: 'Community Gardens',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    lat: 14.5712,
    lng: 121.0608,
    description: 'Communal vegetable plot utilizing organic compost from household food scraps.',
    condition: 'Active',
    details: 'Contains eggplant, tomatoes, sitao, and herbs.',
    photoUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'ast-3',
    name: 'Smart Waste Sorting Hub',
    category: 'Recycling Stations',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    lat: 14.5722,
    lng: 121.0627,
    description: '24/7 accessible segregated collection hub with electronic weight loggers.',
    condition: 'Good',
    details: 'Accepts PET plastics, aluminum cans, glass, cardboards.',
  },
  {
    id: 'ast-4',
    name: 'Solar-Powered Park Lighting',
    category: 'Solar Installations',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    lat: 14.5705,
    lng: 121.0612,
    description: '100% off-grid solar LED posts along the barangay green walkway.',
    condition: 'Operational',
  },
  {
    id: 'ast-5',
    name: 'Barangay Hall Rainwater Tank',
    category: 'Rainwater Systems',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    lat: 14.5715,
    lng: 121.0618,
    description: '5,000L rainwater storage for street washing and watering street plants.',
    condition: 'Operational',
  },
];

export const INITIAL_ALERTS: EnvironmentalAlert[] = [
  {
    id: 'alt-1',
    title: 'Flooding Alert: Pasig River Creek Spillover Risk',
    description: 'Monsoon rains caused water level rise along Lowland Creek. Please secure household waste bins to prevent floating debris clogging drainage.',
    category: 'Flooding',
    targetScope: 'City',
    targetId: 'PASIG',
    targetName: 'Pasig City',
    severity: 'High',
    createdAt: '2026-08-11T02:00:00Z',
    active: true,
    authorName: 'Pasig DRRMO & CENRO',
  },
  {
    id: 'alt-2',
    title: 'E-Waste Drive & Hazardous Battery Collection',
    description: 'Special collection box available at Barangay Hall lobby until Friday for toxic household electronic waste.',
    category: 'Hazardous Waste Incident',
    targetScope: 'Barangay',
    targetId: 'brgy-kapitolyo',
    targetName: 'Kapitolyo',
    severity: 'Low',
    createdAt: '2026-08-10T09:00:00Z',
    active: true,
    authorName: 'Brgy. Kapitolyo Eco Committee',
  },
];

export const INITIAL_BULK_PICKUPS: BulkWastePickupRequest[] = [];

export const INITIAL_BUSINESSES: EcoBusiness[] = [
  {
    id: 'biz-1',
    name: 'Ecofill Refillable Home & Body Hub',
    category: 'Refill Station',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    address: '45 East Capitol Drive, Brgy. Kapitolyo',
    contactPhone: '+63 918 888 7766',
    openingHours: '09:00 AM - 07:00 PM (Mon-Sat)',
    services: ['Bring Your Own Container (BYOC)', 'Liquid Detergent Refills', 'Shampoo Refills', 'Biodegradable Soaps'],
    verified: true,
    photoUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=400',
    lat: 14.5719,
    lng: 121.0622,
    rating: 4.9,
  },
  {
    id: 'biz-2',
    name: 'GreenLoop Gadget & Appliance Repair Shop',
    category: 'Repair Shop',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    address: '12 Pioneer St, Brgy. Kapitolyo',
    contactPhone: '+63 920 111 2233',
    openingHours: '10:00 AM - 06:00 PM (Mon-Fri)',
    services: ['Electronics Diagnostics', 'Smartphone Component Repair', 'Small Appliance Fixing'],
    verified: true,
    lat: 14.5710,
    lng: 121.0615,
    rating: 4.7,
  },
  {
    id: 'biz-3',
    name: 'EcoMart Zero-Waste Grocery Store',
    category: 'Zero-Waste Store',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    address: '88 Capitol Commons, Brgy. Kapitolyo',
    contactPhone: '+63 917 555 4433',
    openingHours: '08:00 AM - 08:00 PM Daily',
    services: ['Bulk Organic Grains', 'Bamboo Toothbrushes', 'Compostable Food Wraps'],
    verified: true,
    lat: 14.5730,
    lng: 121.0635,
    rating: 4.8,
  },
];

export const INITIAL_ORGANIZATIONS: PartnerOrganization[] = [
  {
    id: 'org-1',
    name: 'Kapitolyo Elementary Eco Club',
    type: 'School',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    verified: true,
    description: 'Student-led environmental advocacy group conducting campus recycling drives.',
    contactEmail: 'ecoclub@kapitolyoes.edu.ph',
    eventsCreatedCount: 5,
  },
  {
    id: 'org-2',
    name: 'Earth Savers Metro Alliance',
    type: 'NGO',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    verified: true,
    description: 'Regional non-profit focused on urban riverway restoration and plastic diversion.',
    contactEmail: 'contact@earthsavers.org.ph',
    eventsCreatedCount: 12,
  },
];

export const INITIAL_FAMILY_GROUPS: FamilyGroup[] = [];

export const INITIAL_TREES: TreeItem[] = [];

export const INITIAL_CALENDAR_EVENTS: PersonalCalendarEvent[] = [];

export const INITIAL_BARANGAY_IMPROVEMENTS: BarangayImprovement[] = [
  {
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    previousScore: 86.6,
    currentScore: 90.0,
    scoreImprovement: 3.4,
    rankImprovement: 2,
    timeframe: 'Monthly',
  },
  {
    barangayId: 'brgy-san-antonio',
    barangayName: 'San Antonio',
    cityName: 'Pasig City',
    previousScore: 82.1,
    currentScore: 87.2,
    scoreImprovement: 5.1,
    rankImprovement: 4,
    timeframe: 'Monthly',
  },
  {
    barangayId: 'brgy-loyola-heights',
    barangayName: 'Loyola Heights',
    cityName: 'Quezon City',
    previousScore: 81.0,
    currentScore: 85.8,
    scoreImprovement: 4.8,
    rankImprovement: 3,
    timeframe: 'Monthly',
  },
];



