import {
  Region,
  Province,
  City,
  Barangay,
  User,
  Facility,
  EnvironmentalReport,
  Event,
  Challenge,
  GarbageSchedule,
  UserActivityLog,
  Announcement,
  FeedPost,
  GovernmentPage,
  AppNotification,
  EcoProject,
  CommunityPoll,
  EnvironmentalAsset,
  EnvironmentalAlert,
  BulkWastePickupRequest,
  EcoBusiness,
  PartnerOrganization,
  FamilyGroup,
  TreeItem,
  PersonalCalendarEvent,
  BarangayImprovement
} from '../types';

export const INITIAL_REGIONS: Region[] = [
  { code: 'NCR', name: 'National Capital Region (NCR)' },
  { code: 'CAR', name: 'Cordillera Administrative Region (CAR)' },
  { code: 'R01', name: 'Region I - Ilocos Region' },
  { code: 'R02', name: 'Region II - Cagayan Valley' },
  { code: 'R03', name: 'Region III - Central Luzon' },
  { code: 'R04A', name: 'Region IV-A - CALABARZON' },
  { code: 'R04B', name: 'Region IV-B - MIMAROPA' },
  { code: 'R05', name: 'Region V - Bicol Region' },
  { code: 'R06', name: 'Region VI - Western Visayas' },
  { code: 'R07', name: 'Region VII - Central Visayas' },
  { code: 'R08', name: 'Region VIII - Eastern Visayas' },
  { code: 'R09', name: 'Region IX - Zamboanga Peninsula' },
  { code: 'R10', name: 'Region X - Northern Mindanao' },
  { code: 'R11', name: 'Region XI - Davao Region' },
  { code: 'R12', name: 'Region XII - SOCCSKSARGEN' },
  { code: 'R13', name: 'Region XIII - Caraga' },
  { code: 'BARMM', name: 'Bangsamoro Autonomous Region (BARMM)' },
];

export const INITIAL_PROVINCES: Province[] = [
  { code: 'MM', name: 'Metro Manila', regionCode: 'NCR' },
  { code: 'BGT', name: 'Benguet', regionCode: 'CAR' },
  { code: 'BUL', name: 'Bulacan', regionCode: 'R03' },
  { code: 'PAM', name: 'Pampanga', regionCode: 'R03' },
  { code: 'CAV', name: 'Cavite', regionCode: 'R04A' },
  { code: 'LAG', name: 'Laguna', regionCode: 'R04A' },
  { code: 'BAT', name: 'Batangas', regionCode: 'R04A' },
  { code: 'CEB', name: 'Cebu', regionCode: 'R07' },
  { code: 'ILO', name: 'Iloilo', regionCode: 'R06' },
  { code: 'DAV', name: 'Davao del Sur', regionCode: 'R11' },
];

export const INITIAL_CITIES: City[] = [
  // NCR
  { code: 'PASIG', name: 'Pasig City', provinceCode: 'MM', regionCode: 'NCR', isNCR: true },
  { code: 'MAKATI', name: 'Makati City', provinceCode: 'MM', regionCode: 'NCR', isNCR: true },
  { code: 'QC', name: 'Quezon City', provinceCode: 'MM', regionCode: 'NCR', isNCR: true },
  { code: 'MANILA', name: 'City of Manila', provinceCode: 'MM', regionCode: 'NCR', isNCR: true },
  { code: 'TAGUIG', name: 'Taguig City', provinceCode: 'MM', regionCode: 'NCR', isNCR: true },
  { code: 'MANDA', name: 'Mandaluyong City', provinceCode: 'MM', regionCode: 'NCR', isNCR: true },
  // CAR
  { code: 'BAGUIO', name: 'Baguio City', provinceCode: 'BGT', regionCode: 'CAR', isIndependent: true },
  // Cavite
  { code: 'DASMA', name: 'Dasmariñas City', provinceCode: 'CAV', regionCode: 'R04A' },
  // Cebu
  { code: 'CEBUC', name: 'Cebu City', provinceCode: 'CEB', regionCode: 'R07', isIndependent: true },
  // Davao
  { code: 'DAVAOC', name: 'Davao City', provinceCode: 'DAV', regionCode: 'R11', isIndependent: true },
];

export const INITIAL_BARANGAYS: Barangay[] = [
  // Pasig City
  {
    id: 'brgy-kapitolyo',
    psgcCode: '137403011',
    name: 'Kapitolyo',
    cityCode: 'PASIG',
    cityName: 'Pasig City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.5714,
    lng: 121.0617,
    population: 18500,
    totalUsers: 1240,
    score: {
      wasteManagement: 23,
      recycling: 18,
      communityParticipation: 18,
      reportsResolution: 14,
      cleanupActivities: 9,
      sustainabilityChallenges: 4,
      educationParticipation: 4,
      totalScore: 90,
      tier: 'Platinum',
    },
    totalRecycledKg: 18700,
    totalReportsResolved: 128,
    totalReportsReceived: 135,
    mrfActive: true,
    garbageScheduleDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
  },
  {
    id: 'brgy-san-antonio-pasig',
    psgcCode: '137403022',
    name: 'San Antonio',
    cityCode: 'PASIG',
    cityName: 'Pasig City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.5826,
    lng: 121.0658,
    population: 21300,
    totalUsers: 890,
    score: {
      wasteManagement: 21,
      recycling: 17,
      communityParticipation: 16,
      reportsResolution: 13,
      cleanupActivities: 8,
      sustainabilityChallenges: 4,
      educationParticipation: 3,
      totalScore: 82,
      tier: 'Gold',
    },
    totalRecycledKg: 14500,
    totalReportsResolved: 94,
    totalReportsReceived: 105,
    mrfActive: true,
    garbageScheduleDays: ['Tuesday', 'Thursday', 'Saturday'],
  },
  {
    id: 'brgy-oranbo',
    psgcCode: '137403018',
    name: 'Oranbo',
    cityCode: 'PASIG',
    cityName: 'Pasig City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.5768,
    lng: 121.0632,
    population: 8900,
    totalUsers: 450,
    score: {
      wasteManagement: 19,
      recycling: 15,
      communityParticipation: 15,
      reportsResolution: 11,
      cleanupActivities: 7,
      sustainabilityChallenges: 3,
      educationParticipation: 3,
      totalScore: 73,
      tier: 'Silver',
    },
    totalRecycledKg: 6200,
    totalReportsResolved: 45,
    totalReportsReceived: 58,
    mrfActive: false,
    garbageScheduleDays: ['Monday', 'Thursday'],
  },
  {
    id: 'brgy-ugong-pasig',
    psgcCode: '137403030',
    name: 'Ugong',
    cityCode: 'PASIG',
    cityName: 'Pasig City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.5898,
    lng: 121.0776,
    population: 26400,
    totalUsers: 1120,
    score: {
      wasteManagement: 22,
      recycling: 18,
      communityParticipation: 17,
      reportsResolution: 13,
      cleanupActivities: 8,
      sustainabilityChallenges: 4,
      educationParticipation: 4,
      totalScore: 86,
      tier: 'Gold',
    },
    totalRecycledKg: 16800,
    totalReportsResolved: 110,
    totalReportsReceived: 122,
    mrfActive: true,
    garbageScheduleDays: ['Monday', 'Wednesday', 'Friday'],
  },
  // Makati City
  {
    id: 'brgy-san-lorenzo-makati',
    psgcCode: '137602025',
    name: 'San Lorenzo',
    cityCode: 'MAKATI',
    cityName: 'Makati City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.5512,
    lng: 121.0189,
    population: 13200,
    totalUsers: 1280,
    score: {
      wasteManagement: 24,
      recycling: 19,
      communityParticipation: 19,
      reportsResolution: 15,
      cleanupActivities: 9,
      sustainabilityChallenges: 5,
      educationParticipation: 4,
      totalScore: 95,
      tier: 'Platinum',
    },
    totalRecycledKg: 22400,
    totalReportsResolved: 142,
    totalReportsReceived: 145,
    mrfActive: true,
    garbageScheduleDays: ['Daily Morning Collection'],
  },
  {
    id: 'brgy-bel-air',
    psgcCode: '137602003',
    name: 'Bel-Air',
    cityCode: 'MAKATI',
    cityName: 'Makati City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.5604,
    lng: 121.0281,
    population: 18200,
    totalUsers: 950,
    score: {
      wasteManagement: 23,
      recycling: 18,
      communityParticipation: 17,
      reportsResolution: 14,
      cleanupActivities: 8,
      sustainabilityChallenges: 4,
      educationParticipation: 4,
      totalScore: 88,
      tier: 'Gold',
    },
    totalRecycledKg: 15900,
    totalReportsResolved: 88,
    totalReportsReceived: 92,
    mrfActive: true,
    garbageScheduleDays: ['Monday', 'Wednesday', 'Friday', 'Sunday'],
  },
  {
    id: 'brgy-poblacion-makati',
    psgcCode: '137602021',
    name: 'Poblacion',
    cityCode: 'MAKATI',
    cityName: 'Makati City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.5678,
    lng: 121.0312,
    population: 21100,
    totalUsers: 780,
    score: {
      wasteManagement: 18,
      recycling: 14,
      communityParticipation: 15,
      reportsResolution: 11,
      cleanupActivities: 6,
      sustainabilityChallenges: 3,
      educationParticipation: 3,
      totalScore: 70,
      tier: 'Silver',
    },
    totalRecycledKg: 8900,
    totalReportsResolved: 62,
    totalReportsReceived: 82,
    mrfActive: true,
    garbageScheduleDays: ['Tuesday', 'Thursday', 'Saturday'],
  },
  // Quezon City
  {
    id: 'brgy-batasan-hills',
    psgcCode: '137404006',
    name: 'Batasan Hills',
    cityCode: 'QC',
    cityName: 'Quezon City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.6854,
    lng: 121.0924,
    population: 161000,
    totalUsers: 2450,
    score: {
      wasteManagement: 17,
      recycling: 13,
      communityParticipation: 14,
      reportsResolution: 10,
      cleanupActivities: 6,
      sustainabilityChallenges: 2,
      educationParticipation: 3,
      totalScore: 65,
      tier: 'Bronze',
    },
    totalRecycledKg: 19800,
    totalReportsResolved: 154,
    totalReportsReceived: 210,
    mrfActive: true,
    garbageScheduleDays: ['Monday', 'Wednesday', 'Friday'],
  },
  {
    id: 'brgy-loyola-heights',
    psgcCode: '137404052',
    name: 'Loyola Heights',
    cityCode: 'QC',
    cityName: 'Quezon City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.6402,
    lng: 121.0721,
    population: 22400,
    totalUsers: 1420,
    score: {
      wasteManagement: 23,
      recycling: 18,
      communityParticipation: 18,
      reportsResolution: 14,
      cleanupActivities: 9,
      sustainabilityChallenges: 4,
      educationParticipation: 5,
      totalScore: 91,
      tier: 'Platinum',
    },
    totalRecycledKg: 21000,
    totalReportsResolved: 98,
    totalReportsReceived: 102,
    mrfActive: true,
    garbageScheduleDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
  },
  // Manila City
  {
    id: 'brgy-sampaloc-zone-41',
    psgcCode: '133900001',
    name: 'Barangay 411 (Sampaloc)',
    cityCode: 'MANILA',
    cityName: 'City of Manila',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.6082,
    lng: 120.9942,
    population: 12800,
    totalUsers: 540,
    score: {
      wasteManagement: 15,
      recycling: 11,
      communityParticipation: 12,
      reportsResolution: 8,
      cleanupActivities: 5,
      sustainabilityChallenges: 2,
      educationParticipation: 2,
      totalScore: 55,
      tier: 'Developing',
    },
    totalRecycledKg: 4200,
    totalReportsResolved: 32,
    totalReportsReceived: 56,
    mrfActive: false,
    garbageScheduleDays: ['Tuesday', 'Thursday', 'Saturday'],
  },
  // Taguig City
  {
    id: 'brgy-fort-bonifacio',
    psgcCode: '137607008',
    name: 'Fort Bonifacio (BGC)',
    cityCode: 'TAGUIG',
    cityName: 'Taguig City',
    provinceCode: 'MM',
    provinceName: 'Metro Manila',
    regionCode: 'NCR',
    regionName: 'NCR',
    lat: 14.5519,
    lng: 121.0494,
    population: 28900,
    totalUsers: 1890,
    score: {
      wasteManagement: 24,
      recycling: 19,
      communityParticipation: 18,
      reportsResolution: 14,
      cleanupActivities: 8,
      sustainabilityChallenges: 5,
      educationParticipation: 4,
      totalScore: 92,
      tier: 'Platinum',
    },
    totalRecycledKg: 28500,
    totalReportsResolved: 165,
    totalReportsReceived: 170,
    mrfActive: true,
    garbageScheduleDays: ['Daily Evening Collection'],
  },
  // Cebu City
  {
    id: 'brgy-lahug-cebu',
    psgcCode: '072217032',
    name: 'Lahug',
    cityCode: 'CEBUC',
    cityName: 'Cebu City',
    provinceCode: 'CEB',
    provinceName: 'Cebu',
    regionCode: 'R07',
    regionName: 'Region VII - Central Visayas',
    lat: 10.3341,
    lng: 123.8964,
    population: 38200,
    totalUsers: 840,
    score: {
      wasteManagement: 20,
      recycling: 16,
      communityParticipation: 16,
      reportsResolution: 12,
      cleanupActivities: 7,
      sustainabilityChallenges: 3,
      educationParticipation: 4,
      totalScore: 78,
      tier: 'Gold',
    },
    totalRecycledKg: 11200,
    totalReportsResolved: 72,
    totalReportsReceived: 88,
    mrfActive: true,
    garbageScheduleDays: ['Monday', 'Wednesday', 'Friday'],
  },
  // Davao City
  {
    id: 'brgy-poblacion-davao',
    psgcCode: '112402001',
    name: 'Poblacion District',
    cityCode: 'DAVAOC',
    cityName: 'Davao City',
    provinceCode: 'DAV',
    provinceName: 'Davao del Sur',
    regionCode: 'R11',
    regionName: 'Region XI - Davao Region',
    lat: 7.0731,
    lng: 125.6128,
    population: 45000,
    totalUsers: 1150,
    score: {
      wasteManagement: 22,
      recycling: 17,
      communityParticipation: 17,
      reportsResolution: 13,
      cleanupActivities: 8,
      sustainabilityChallenges: 4,
      educationParticipation: 4,
      totalScore: 85,
      tier: 'Gold',
    },
    totalRecycledKg: 15400,
    totalReportsResolved: 95,
    totalReportsReceived: 108,
    mrfActive: true,
    garbageScheduleDays: ['Tuesday', 'Thursday', 'Saturday'],
  },
  // Baguio City
  {
    id: 'brgy-burnham-baguio',
    psgcCode: '141102010',
    name: 'Burnham - Legarda',
    cityCode: 'BAGUIO',
    cityName: 'Baguio City',
    provinceCode: 'BGT',
    provinceName: 'Benguet',
    regionCode: 'CAR',
    regionName: 'CAR',
    lat: 16.4111,
    lng: 120.5955,
    population: 14200,
    totalUsers: 620,
    score: {
      wasteManagement: 21,
      recycling: 16,
      communityParticipation: 16,
      reportsResolution: 12,
      cleanupActivities: 8,
      sustainabilityChallenges: 3,
      educationParticipation: 3,
      totalScore: 79,
      tier: 'Silver',
    },
    totalRecycledKg: 9800,
    totalReportsResolved: 58,
    totalReportsReceived: 66,
    mrfActive: true,
    garbageScheduleDays: ['Monday', 'Wednesday', 'Friday'],
  },
];

export const INITIAL_GOVERNMENT_PAGES: GovernmentPage[] = [
  {
    id: 'gov-denr',
    name: 'Department of Environment and Natural Resources',
    acronym: 'DENR Central',
    category: 'National Agency',
    description: 'Official national executive department responsible for governing, conserving, and protecting the Philippines\' natural resources and environment under RA 9003.',
    avatarUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=200',
    coverUrl: 'https://images.unsplash.com/photo-1511497584788-876761c11969?auto=format&fit=crop&q=80&w=800',
    verified: true,
    followersCount: 14250,
    website: 'https://denr.gov.ph',
  },
  {
    id: 'gov-mmda',
    name: 'MMDA Solid Waste Management Office',
    acronym: 'MMDA',
    category: 'LGU Office',
    description: 'Metropolitan Manila Development Authority supervising waste management, flood control, and environmental sanitation across 17 LGUs in NCR.',
    avatarUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80&w=200',
    verified: true,
    followersCount: 9800,
    regionCode: 'NCR',
    website: 'https://mmda.gov.ph',
  },
  {
    id: 'gov-pasig-cenro',
    name: 'Pasig City Environment & Natural Resources Office',
    acronym: 'Pasig CENRO',
    category: 'LGU Office',
    description: 'Lead environmental agency of Pasig City driving urban greening, MRF operations, river cleanup, and zero-waste household segregation.',
    avatarUrl: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&q=80&w=200',
    verified: true,
    followersCount: 6540,
    regionCode: 'NCR',
    cityCode: 'PASIG',
    cityName: 'Pasig City',
  },
  {
    id: 'gov-brgy-kapitolyo',
    name: 'Barangay Kapitolyo Official Govt Page',
    acronym: 'Brgy Kapitolyo Council',
    category: 'Barangay Office',
    description: 'Official local government page of Brgy. Kapitolyo, Pasig City. Providing waste collection schedules, MRF updates, and community cleanup drives.',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    verified: true,
    followersCount: 3820,
    regionCode: 'NCR',
    cityCode: 'PASIG',
    cityName: 'Pasig City',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
  },
  {
    id: 'gov-ccc',
    name: 'Climate Change Commission Philippines',
    acronym: 'CCC PH',
    category: 'National Agency',
    description: 'Lead policy-making body of the government tasked to coordinate, monitor and evaluate climate change programs and sustainable barangay action plans.',
    avatarUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=200',
    verified: true,
    followersCount: 11200,
  },
  {
    id: 'gov-cebu-cenro',
    name: 'Cebu City Environment & Natural Resources Office',
    acronym: 'Cebu CCENRO',
    category: 'LGU Office',
    description: 'Promoting clean waterways, zero single-use plastic mandates, and coastal resource conservation across Cebu City barangays.',
    avatarUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=200',
    verified: true,
    followersCount: 5200,
    regionCode: 'R07',
    cityCode: 'CEBUC',
    cityName: 'Cebu City',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-resident-1',
    email: 'resident@ecobarangay.ph',
    fullName: 'Maria Santos',
    role: 'RESIDENT',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    city: 'Pasig City',
    province: 'Metro Manila',
    region: 'NCR',
    phone: '09171234567',
    ecoPoints: 1250,
    ecoScore: 78,
    kgRecycled: 45,
    challengesCompleted: 8,
    cleanupActivitiesCount: 3,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    followingUserIds: ['user-official-1'],
    followingPageIds: ['gov-denr', 'gov-pasig-cenro', 'gov-brgy-kapitolyo'],
  },
  {
    id: 'user-official-1',
    email: 'official@ecobarangay.ph',
    fullName: 'Kapitan Juan Dela Cruz',
    role: 'BARANGAY_OFFICIAL',
    barangayId: 'brgy-san-antonio-pasig',
    barangayName: 'San Antonio',
    city: 'Pasig City',
    province: 'Metro Manila',
    region: 'NCR',
    phone: '09189876543',
    ecoPoints: 3400,
    ecoScore: 92,
    kgRecycled: 120,
    challengesCompleted: 15,
    cleanupActivitiesCount: 12,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    verifiedOfficial: true,
    followingUserIds: ['user-resident-1'],
    followingPageIds: ['gov-denr', 'gov-mmda', 'gov-pasig-cenro'],
  },
  {
    id: 'user-admin-1',
    email: 'admin@ecobarangay.ph',
    fullName: 'Admin Sofia Reyes',
    role: 'SYSTEM_ADMIN',
    barangayId: 'brgy-fort-bonifacio',
    barangayName: 'Fort Bonifacio (BGC)',
    city: 'Taguig City',
    province: 'Metro Manila',
    region: 'NCR',
    phone: '09195551234',
    ecoPoints: 9990,
    ecoScore: 99,
    kgRecycled: 350,
    challengesCompleted: 25,
    cleanupActivitiesCount: 20,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    verifiedOfficial: true,
    followingUserIds: ['user-resident-1', 'user-official-1'],
    followingPageIds: ['gov-denr', 'gov-mmda', 'gov-ccc', 'gov-pasig-cenro', 'gov-cebu-cenro'],
  },
];

export const INITIAL_FACILITIES: Facility[] = [
  {
    id: 'fac-1',
    name: 'Kapitolyo Eco-Recovery & MRF Center',
    category: 'mrf',
    address: 'East Capitol Drive, Brgy. Kapitolyo',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    city: 'Pasig City',
    province: 'Metro Manila',
    lat: 14.5721,
    lng: 121.0625,
    acceptedMaterials: ['Plastic', 'Paper', 'Glass', 'Cardboard', 'Organics'],
    openingHours: '8:00 AM - 5:00 PM (Mon-Sat)',
    contact: '(02) 8631-1122',
    description: 'Official Materials Recovery Facility of Brgy. Kapitolyo. Provides eco-points exchange for clean dry plastic recyclables.',
  },
  {
    id: 'fac-2',
    name: 'San Antonio Junk Shop & Recycling Hub',
    category: 'junkshop',
    address: 'Shaw Blvd cor. San Antonio St.',
    barangayId: 'brgy-san-antonio-pasig',
    barangayName: 'San Antonio',
    city: 'Pasig City',
    province: 'Metro Manila',
    lat: 14.5815,
    lng: 121.0642,
    acceptedMaterials: ['Scrap Metal', 'Copper', 'Aluminum Cans', 'PET Bottles', 'Paper'],
    openingHours: '7:30 AM - 6:00 PM Daily',
    contact: '0920-444-1234',
    description: 'Community-accredited junk shop purchasing household scrap metals, batteries, and bulk plastics at fair daily market rates.',
  },
  {
    id: 'fac-3',
    name: 'Ortigas E-Waste Drop-off Hub',
    category: 'ewaste',
    address: 'F. Ortigas Jr. Road, Ortigas Center',
    barangayId: 'brgy-san-antonio-pasig',
    barangayName: 'San Antonio',
    city: 'Pasig City',
    province: 'Metro Manila',
    lat: 14.5842,
    lng: 121.0601,
    acceptedMaterials: ['Old Laptops', 'Cellphones', 'Batteries', 'Chargers', 'Circuit Boards'],
    openingHours: '9:00 AM - 7:00 PM (Mon-Fri)',
    contact: '(02) 8687-9900',
    description: 'Safe electronic waste drop-off station ensuring hazardous components are diverted from landfills and recycled responsibly.',
  },
  {
    id: 'fac-4',
    name: 'Pasig Central Organic Composting Park',
    category: 'composting',
    address: 'Caruncho Ave, Brgy. San Nicolas',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    city: 'Pasig City',
    province: 'Metro Manila',
    lat: 14.5605,
    lng: 121.0805,
    acceptedMaterials: ['Fruit Scraps', 'Vegetable Waste', 'Dry Leaves', 'Coffee Grounds'],
    openingHours: '6:00 AM - 4:00 PM (Daily)',
    contact: '(02) 8643-0000',
    description: 'Community vermi-composting facility converting kitchen food waste into rich organic fertilizer for barangay urban gardens.',
  },
  {
    id: 'fac-5',
    name: 'San Lorenzo Eco-Hub & Bottle Bank',
    category: 'recycling',
    address: 'Amorsolo St, Brgy. San Lorenzo',
    barangayId: 'brgy-san-lorenzo-makati',
    barangayName: 'San Lorenzo',
    city: 'Makati City',
    province: 'Metro Manila',
    lat: 14.5501,
    lng: 121.0175,
    acceptedMaterials: ['Glass Bottles', 'PET Containers', 'Tetra Pak', 'Aluminum'],
    openingHours: '8:00 AM - 6:00 PM (Mon-Sat)',
    contact: '(02) 8812-3456',
    description: 'Award-winning recycling drop-off depot with digital weight scales and instant app Eco Points credit.',
  },
  {
    id: 'fac-6',
    name: 'Batasan Green Community MRF',
    category: 'mrf',
    address: 'Batasan-San Mateo Road, QC',
    barangayId: 'brgy-batasan-hills',
    barangayName: 'Batasan Hills',
    city: 'Quezon City',
    province: 'Metro Manila',
    lat: 14.6882,
    lng: 121.0945,
    acceptedMaterials: ['Plastic', 'Paper', 'Glass', 'Cardboard', 'Metal'],
    openingHours: '7:00 AM - 5:00 PM (Mon-Fri)',
    contact: '(02) 8931-5000',
    description: 'Large-capacity sorting facility serving Batasan Hills residents and local market vendors.',
  },
];

export const INITIAL_REPORTS: EnvironmentalReport[] = [
  {
    id: 'rep-1',
    category: 'Illegal Dumping',
    description: 'Large pile of uncollected plastic bags and construction debris along West Capitol Drive sidewalk.',
    locationAddress: 'Corner West Capitol Drive & Pioneer St, Brgy. Kapitolyo',
    lat: 14.5705,
    lng: 121.0608,
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    reporterId: 'user-resident-1',
    reporterName: 'Maria Santos',
    photoUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&q=80&w=600',
    status: 'In Progress',
    createdAt: '2026-08-07T09:30:00Z',
    officialNotes: 'Eco-clean truck dispatched for pickup on Aug 9 morning.',
  },
  {
    id: 'rep-2',
    category: 'Overflowing Bin',
    description: 'Public segregation bins near Kapitolyo Park are full and overflowing onto the pedestrian path.',
    locationAddress: 'Kapitolyo Park Main Entrance',
    lat: 14.5728,
    lng: 121.0620,
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    reporterId: 'user-resident-1',
    reporterName: 'Maria Santos',
    photoUrl: 'https://images.unsplash.com/photo-1611284446314-60a55ac0d49d?auto=format&fit=crop&q=80&w=600',
    status: 'Resolved',
    createdAt: '2026-08-05T14:15:00Z',
    resolvedAt: '2026-08-06T10:00:00Z',
    officialNotes: 'Bins emptied and replaced with larger 240L dual-stream bins.',
  },
  {
    id: 'rep-3',
    category: 'Missed Collection',
    description: 'Biodegradable trash trucks missed Street 4 during the Tuesday morning route.',
    locationAddress: 'Pearl Drive, Brgy. San Antonio',
    lat: 14.5821,
    lng: 121.0648,
    barangayId: 'brgy-san-antonio-pasig',
    barangayName: 'San Antonio',
    cityName: 'Pasig City',
    reporterId: 'user-official-1',
    reporterName: 'Kapitan Juan Dela Cruz',
    status: 'Pending',
    createdAt: '2026-08-08T16:45:00Z',
    officialNotes: 'Garbage inspector notified to review driver GPS log.',
  },
];

export const INITIAL_EVENTS: Event[] = [
  {
    id: 'evt-1',
    title: 'Weekend Marikina Riverbanks Cleanup Drive',
    description: 'Join neighbors in collecting floating plastics, riverbank litter, and planting vetiver grass along the waterway.',
    date: '2026-08-15',
    time: '06:30 AM - 09:30 AM',
    location: 'Marikina River Park Promenade (Kapitolyo Boundary)',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    organizerName: 'Barangay Kapitolyo Environmental Committee',
    category: 'Cleanup',
    pointsAwarded: 150,
    registeredUserIds: ['user-resident-1', 'user-official-1'],
    maxParticipants: 60,
    lat: 14.5742,
    lng: 121.0665,
  },
  {
    id: 'evt-2',
    title: 'Household Vermi-Composting Workshop & Free Starter Kit',
    description: 'Learn how to turn kitchen food scraps into nutrient-rich garden soil using African Nightcrawler worms.',
    date: '2026-08-22',
    time: '02:00 PM - 04:30 PM',
    location: 'San Antonio Community Covered Court',
    barangayId: 'brgy-san-antonio-pasig',
    barangayName: 'San Antonio',
    organizerName: 'LGU Pasig City Clean & Green Team',
    category: 'Workshop',
    pointsAwarded: 100,
    registeredUserIds: ['user-official-1'],
    maxParticipants: 40,
    lat: 14.5831,
    lng: 121.0660,
  },
  {
    id: 'evt-3',
    title: 'Trash to Cash Electronic & Plastic Exchange',
    description: 'Bring old appliances, glass, plastic bottles, and paper in exchange for eco points, sacks of rice, or groceries.',
    date: '2026-08-29',
    time: '08:00 AM - 12:00 PM',
    location: 'Kapitolyo Multi-Purpose Center Grounds',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    organizerName: 'EcoBarangay Alliance & Pasig LGU',
    category: 'Recycling Drive',
    pointsAwarded: 120,
    registeredUserIds: ['user-resident-1'],
    maxParticipants: 150,
    lat: 14.5718,
    lng: 121.0612,
  },
];

export const INITIAL_CHALLENGES: Challenge[] = [
  {
    id: 'chl-1',
    title: '7-Day Zero Single-Use Plastic Week',
    description: 'Avoid single-use plastic water bottles, plastic straws, and plastic shopping bags for 7 consecutive days.',
    category: 'Waste Reduction',
    durationDays: 7,
    pointsAwarded: 200,
    icon: 'no_drinks',
    joinedUserIds: ['user-resident-1', 'user-official-1'],
    completedUserIds: ['user-resident-1'],
  },
  {
    id: 'chl-2',
    title: 'Segregate 10kg Recyclables Challenge',
    description: 'Separate PET bottles, clean cardboard, and metal cans at home and drop them off at your nearest MRF.',
    category: 'Recycling',
    durationDays: 14,
    pointsAwarded: 250,
    icon: 'recycling',
    joinedUserIds: ['user-resident-1'],
    completedUserIds: [],
  },
  {
    id: 'chl-3',
    title: 'Community Environmental Champion',
    description: 'Report 3 environmental problems or illegal dumping sites in your neighborhood to help LGU cleanups.',
    category: 'Reporting & Civic Duty',
    durationDays: 30,
    pointsAwarded: 300,
    icon: 'campaign',
    joinedUserIds: ['user-resident-1', 'user-official-1'],
    completedUserIds: [],
  },
  {
    id: 'chl-4',
    title: 'Kitchen Scraps Composting Pioneer',
    description: 'Divert 5kg of kitchen food scraps to a backyard pit, vermi bin, or community composting facility.',
    category: 'Composting',
    durationDays: 10,
    pointsAwarded: 180,
    icon: 'eco',
    joinedUserIds: [],
    completedUserIds: [],
  },
];

export const INITIAL_SCHEDULES: GarbageSchedule[] = [
  {
    id: 'sch-1',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    dayOfWeek: 'Monday & Thursday',
    timeSlot: '06:00 AM - 09:00 AM',
    wasteType: 'Biodegradable',
    instructions: 'Place food waste, garden trimmings, and organic material in green bags or covered bins outside gate.',
    truckNo: 'Truck #04 (Pasig Solid Waste)',
  },
  {
    id: 'sch-2',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    dayOfWeek: 'Tuesday & Friday',
    timeSlot: '06:00 AM - 09:00 AM',
    wasteType: 'Non-Biodegradable',
    instructions: 'Residual non-recyclable household waste tied securely in black plastic bags.',
    truckNo: 'Truck #08 (Pasig Solid Waste)',
  },
  {
    id: 'sch-3',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    dayOfWeek: 'Saturday',
    timeSlot: '08:00 AM - 12:00 PM',
    wasteType: 'Recyclable',
    instructions: 'Cleaned plastics, bottles, cardboard boxes, and tin cans tied or boxed separately for MRF pickup.',
    truckNo: 'Eco-Recycling Truck #01',
  },
  {
    id: 'sch-4',
    barangayId: 'brgy-san-antonio-pasig',
    barangayName: 'San Antonio',
    dayOfWeek: 'Monday, Wednesday, Friday',
    timeSlot: '07:00 AM - 10:00 AM',
    wasteType: 'Biodegradable',
    instructions: 'Must be segregated in labeled containers. Wet waste will not be collected if mixed with plastic.',
    truckNo: 'Truck #12',
  },
];

export const INITIAL_ACTIVITY_LOGS: UserActivityLog[] = [
  {
    id: 'act-1',
    userId: 'user-resident-1',
    type: 'Recycling',
    title: 'Dropped off recyclables at Kapitolyo MRF',
    description: '5.2 kg of clean PET plastic water bottles and cardboard boxes.',
    pointsEarned: 50,
    kgRecycled: 5.2,
    createdAt: '2026-08-08T11:20:00Z',
  },
  {
    id: 'act-2',
    userId: 'user-resident-1',
    type: 'Challenge',
    title: 'Completed 7-Day Plastic Free Challenge',
    description: 'Successfully completed the challenge and earned Sustainability Badge.',
    pointsEarned: 200,
    createdAt: '2026-08-06T18:00:00Z',
  },
  {
    id: 'act-3',
    userId: 'user-resident-1',
    type: 'Report',
    title: 'Submitted environmental report for overflowing bin',
    description: 'Reported issue at Kapitolyo Park entrance.',
    pointsEarned: 30,
    createdAt: '2026-08-05T14:15:00Z',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'anc-1',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    authorName: 'Barangay Kapitolyo Council',
    title: 'Strict Implementation of RA 9003 Waste Segregation',
    content: 'Starting Aug 15, unsegregated trash will NOT be collected. Please ensure separate bins for Biodegradable (Nabubulok), Non-Biodegradable (Di-Nabubulok), and Recyclable items.',
    category: 'Urgent',
    createdAt: '2026-08-08T08:00:00Z',
  },
  {
    id: 'anc-2',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    authorName: 'Kapitolyo Eco-Center',
    title: 'Free Compost Soil Distribution for Residents',
    content: 'Residents with active EcoBarangay profiles can claim 2kg of free organic fertilizer at the Barangay Hall garden nursery every Saturday morning.',
    category: 'General',
    createdAt: '2026-08-04T10:30:00Z',
  },
];

export const INITIAL_FEED_POSTS: FeedPost[] = [
  {
    id: 'post-gov-1',
    authorId: 'gov-denr',
    authorName: 'Department of Environment and Natural Resources',
    authorAvatar: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=200',
    authorRole: 'SYSTEM_ADMIN',
    governmentPageId: 'gov-denr',
    isGovernmentPost: true,
    barangayId: 'national',
    barangayName: 'National (DENR)',
    regionCode: 'NCR',
    content: '🏛️ DENR Advisory: Pursuant to Republic Act 9003 (Ecological Solid Waste Management Act), all LGUs and Barangays nationwide are advised to maintain active Material Recovery Facilities (MRFs) and submit monthly waste diversion metrics. Let us build green, sustainable communities together! 🇵🇭',
    photoUrl: 'https://images.unsplash.com/photo-1511497584788-876761c11969?auto=format&fit=crop&q=80&w=800',
    likes: ['user-resident-1', 'user-official-1', 'user-admin-1'],
    comments: [
      {
        id: 'c-gov-1',
        postId: 'post-gov-1',
        authorId: 'user-official-1',
        authorName: 'Kapitan Juan Dela Cruz',
        content: 'Fully compliant here at Pasig City! Our barangay MRF operates 6 days a week.',
        createdAt: '2026-08-09T09:10:00Z',
      },
    ],
    sharesCount: 45,
    createdAt: '2026-08-09T08:00:00Z',
  },
  {
    id: 'post-gov-2',
    authorId: 'gov-pasig-cenro',
    authorName: 'Pasig City Environment & Natural Resources Office',
    authorAvatar: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&q=80&w=200',
    authorRole: 'BARANGAY_OFFICIAL',
    governmentPageId: 'gov-pasig-cenro',
    isGovernmentPost: true,
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    regionCode: 'NCR',
    provinceCode: 'MM',
    cityCode: 'PASIG',
    cityName: 'Pasig City',
    content: '🌱 Pasig City CENRO Update: All Pasig City residents turning in recyclable plastics at any local MRF drop-off location can now claim digital Eco Points and organic compost bags. Check out your nearest barangay hub on the Eco-Map!',
    photoUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=800',
    likes: ['user-resident-1'],
    comments: [],
    sharesCount: 18,
    createdAt: '2026-08-08T15:20:00Z',
  },
  {
    id: 'post-1',
    authorId: 'user-resident-1',
    authorName: 'Maria Santos',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    authorRole: 'RESIDENT',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    regionCode: 'NCR',
    provinceCode: 'MM',
    cityCode: 'PASIG',
    cityName: 'Pasig City',
    content: 'Naitapon ko na ang 5.2kg ng resiklong plastik at karton sa ating Kapitolyo MRF Center! Napakalinis at napaka-organisado ng pasilidad natin. ♻️🇵🇭 #EcoKapitolyo #ZeroWastePH',
    photoUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80&w=800',
    wasteKg: 5.2,
    wasteType: 'PET Plastics & Cardboard',
    likes: ['user-official-1', 'user-admin-1'],
    comments: [
      {
        id: 'c-1',
        postId: 'post-1',
        authorId: 'user-official-1',
        authorName: 'Kapitan Juan Dela Cruz',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
        content: 'Maraming salamat sa iyong patuloy na pagsuporta sa ating zero-waste barangay initiative, Maria! Dagdag +50 EcoPoints para sa iyo!',
        createdAt: '2026-08-08T12:05:00Z',
      },
    ],
    sharesCount: 3,
    createdAt: '2026-08-08T11:25:00Z',
  },
  {
    id: 'post-2',
    authorId: 'user-official-1',
    authorName: 'Kapitan Juan Dela Cruz',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    authorRole: 'BARANGAY_OFFICIAL',
    barangayId: 'brgy-san-antonio-pasig',
    barangayName: 'San Antonio',
    regionCode: 'NCR',
    provinceCode: 'MM',
    cityCode: 'PASIG',
    cityName: 'Pasig City',
    content: 'Inaanyayahan po ang lahat ng residents sa ating upcoming Grand Pasig Riverbank Cleanup Drive ngayong Sabado, 7:00 AM sa Kapitolyo Waterfront! May libreng eco-tote bag at snacks para sa unang 50 volunteers. Magtulungan tayo para sa mas malinis na barangay!',
    photoUrl: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&q=80&w=800',
    likes: ['user-resident-1'],
    comments: [
      {
        id: 'c-2',
        postId: 'post-2',
        authorId: 'user-resident-1',
        authorName: 'Maria Santos',
        content: 'Kasama po ako at ang aking pamilya! Magdadala rin kami ng sarili naming reusable gloves at sacks.',
        createdAt: '2026-08-07T15:30:00Z',
      },
    ],
    sharesCount: 12,
    createdAt: '2026-08-07T14:00:00Z',
  },
  {
    id: 'post-gov-3',
    authorId: 'gov-cebu-cenro',
    authorName: 'Cebu City Environment & Natural Resources Office',
    authorAvatar: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=200',
    authorRole: 'BARANGAY_OFFICIAL',
    governmentPageId: 'gov-cebu-cenro',
    isGovernmentPost: true,
    barangayId: 'brgy-lahug',
    barangayName: 'Lahug',
    regionCode: 'R07',
    provinceCode: 'CEB',
    cityCode: 'CEBUC',
    cityName: 'Cebu City',
    content: '🌊 Cebu City Coastal Resource Notice: Weekly coastal cleanup drive in Lahug & Mabolo waterways yielded 1.8 tons of plastics now turned into eco-bricks for barangay benches. Daghang salamat sa tanang volunteers!',
    photoUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
    likes: ['user-admin-1'],
    comments: [],
    sharesCount: 22,
    createdAt: '2026-08-06T16:40:00Z',
  },
  {
    id: 'post-3',
    authorId: 'user-admin-1',
    authorName: 'Sofia Reyes (Admin)',
    authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    authorRole: 'SYSTEM_ADMIN',
    barangayId: 'brgy-fort-bonifacio',
    barangayName: 'Fort Bonifacio',
    regionCode: 'NCR',
    provinceCode: 'MM',
    cityCode: 'TAGUIG',
    cityName: 'Taguig City',
    content: 'Congratulations to Brgy. Kapitolyo (Pasig City) for reaching Platinum Tier status on the National Barangay Sustainability Leaderboard! Over 18,700 kg of recyclables diverted from landfills this month.',
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800',
    likes: ['user-resident-1', 'user-official-1'],
    comments: [],
    sharesCount: 8,
    createdAt: '2026-08-06T09:15:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    type: 'RANKING_CHANGE',
    title: '🏆 Barangay Ranking Update',
    message: 'Brgy. Kapitolyo achieved Rank #1 in Pasig City with 18,750 pts (Platinum Tier)!',
    timestamp: '2026-08-10T10:00:00Z',
    read: false,
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    targetTab: 'rankings'
  },
  {
    id: 'notif-2',
    type: 'EVENT_SIGNUP',
    title: '🌱 New Event Participant',
    message: 'Maria Santos registered for "Pasig Riverbank Cleanup & Tree Planting Drive". Total participants: 38/50.',
    timestamp: '2026-08-10T08:30:00Z',
    read: false,
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    targetTab: 'events',
    linkId: 'evt-1'
  },
  {
    id: 'notif-3',
    type: 'REPORT_UPDATE',
    title: '🚨 Environmental Report Resolved',
    message: 'Report #REP-2026-001 (Illegal Garbage Dump near Boulevard) has been resolved by Pasig CENRO team.',
    timestamp: '2026-08-09T16:15:00Z',
    read: false,
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    targetTab: 'reports',
    linkId: 'rep-1'
  }
];

// ==================== NEW FEATURES INITIAL DATA ====================

export const INITIAL_PROJECTS: EcoProject[] = [
  {
    id: 'proj-1',
    title: 'Community Smart Recycling Hub',
    description: 'Establish a central automated sorting station with separate digital bins for plastics, paper, glass, and electronic waste.',
    category: 'Recycling Station',
    status: 'In Progress',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    suggestedByUserId: 'user-resident-1',
    suggestedByName: 'Maria Santos',
    votesCount: 142,
    votedUserIds: ['user-resident-1', 'user-resident-2', 'user-official-1'],
    followersCount: 89,
    followedUserIds: ['user-resident-1', 'user-official-1'],
    progressPercent: 75,
    targetCompletionDate: '2026-09-01',
    beforePhotoUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&q=80&w=800',
    afterPhotoUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80&w=800',
    lat: 14.5720,
    lng: 121.0625,
    updates: [
      {
        id: 'upd-1',
        date: '2026-08-01',
        title: 'Concrete Base & Canopy Installed',
        description: 'Completed structural framework and rainproof roofing for sorting bins.',
        progressPercent: 75,
        photoUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80&w=800',
        authorName: 'Capt. Juan Dela Cruz',
      },
    ],
    feedback: [
      {
        id: 'fb-1',
        authorId: 'user-resident-2',
        authorName: 'Ramon Bautista',
        content: 'Great initiative! Will we have dedicated bins for broken appliances and battery disposals too?',
        createdAt: '2026-08-05T10:15:00Z',
      },
    ],
    createdAt: '2026-07-10T08:00:00Z',
  },
  {
    id: 'proj-2',
    title: 'Kapitolyo Organic Composting Facility',
    description: 'Transform market waste and household food scraps into nutrient-rich organic fertilizer for urban gardens.',
    category: 'Composting Facility',
    status: 'Approved',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    suggestedByUserId: 'user-official-1',
    suggestedByName: 'Capt. Juan Dela Cruz',
    votesCount: 98,
    votedUserIds: ['user-resident-1', 'user-official-1'],
    followersCount: 62,
    followedUserIds: ['user-resident-1'],
    progressPercent: 30,
    targetCompletionDate: '2026-10-15',
    beforePhotoUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=800',
    lat: 14.5710,
    lng: 121.0605,
    updates: [],
    feedback: [],
    createdAt: '2026-07-20T09:30:00Z',
  },
  {
    id: 'proj-3',
    title: 'Rainwater Harvesting & Filtration System',
    description: 'Collect roof runoff water from barangay hall to clean streets and water community garden plots during dry spells.',
    category: 'Solar Installation',
    status: 'Voting',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    suggestedByUserId: 'user-resident-1',
    suggestedByName: 'Maria Santos',
    votesCount: 84,
    votedUserIds: ['user-resident-1'],
    followersCount: 45,
    followedUserIds: ['user-resident-1'],
    progressPercent: 10,
    targetCompletionDate: '2026-11-01',
    lat: 14.5728,
    lng: 121.0630,
    updates: [],
    feedback: [],
    createdAt: '2026-08-01T14:00:00Z',
  },
  {
    id: 'proj-4',
    title: 'Riverbank Urban Tree Planting & Solar Walkway',
    description: 'Cleaned former illegal dumping ground along creek and turned into shaded tree park with solar lanterns.',
    category: 'Tree Planting',
    status: 'Completed',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    suggestedByUserId: 'user-official-1',
    suggestedByName: 'Capt. Juan Dela Cruz',
    votesCount: 210,
    votedUserIds: ['user-resident-1', 'user-resident-2', 'user-official-1'],
    followersCount: 130,
    followedUserIds: ['user-resident-1'],
    progressPercent: 100,
    targetCompletionDate: '2026-07-30',
    beforePhotoUrl: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&q=80&w=800',
    afterPhotoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800',
    lat: 14.5702,
    lng: 121.0610,
    updates: [
      {
        id: 'upd-40',
        date: '2026-07-28',
        title: 'Project Fully Completed!',
        description: 'Planting 120 native Philippine trees and solar poles installation completed.',
        progressPercent: 100,
        photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800',
        authorName: 'Capt. Juan Dela Cruz',
      },
    ],
    feedback: [],
    createdAt: '2026-06-01T08:00:00Z',
  },
];

export const INITIAL_POLLS: CommunityPoll[] = [
  {
    id: 'poll-1',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    title: 'What environmental project should Brgy. Kapitolyo prioritize for Q4 2026?',
    description: 'Vote to decide which sustainability project will receive primary barangay allocation.',
    options: [
      { id: 'opt-1', text: 'More Smart Recycling Bins', votesCount: 124 },
      { id: 'opt-2', text: 'Creek Drainage Cleanout & Trash Traps', votesCount: 98 },
      { id: 'opt-3', text: 'Urban Tree Planting in Park Areas', votesCount: 65 },
      { id: 'opt-4', text: 'Community Composting Facility', votesCount: 42 },
      { id: 'opt-5', text: 'Monthly E-Waste Collection Drive', votesCount: 31 },
    ],
    votedUserIds: [
      { userId: 'user-resident-1', optionId: 'opt-1' },
      { userId: 'user-official-1', optionId: 'opt-2' },
    ],
    totalVotes: 360,
    deadline: '2026-08-30',
    status: 'Active',
    createdAt: '2026-08-01T08:00:00Z',
    createdByOfficialName: 'Capt. Juan Dela Cruz',
  },
];

export const INITIAL_ASSETS: EnvironmentalAsset[] = [
  {
    id: 'ast-1',
    name: 'Kapitolyo Centenary Banaba Tree',
    category: 'Trees',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    lat: 14.5718,
    lng: 121.0620,
    description: 'Heritage shade tree providing natural cooling and bird sanctuary.',
    condition: 'Healthy',
    details: 'Planted 1985. Species: Lagerstroemia speciosa',
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'ast-2',
    name: 'Kapitolyo Urban Community Garden',
    category: 'Community Gardens',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    lat: 14.5712,
    lng: 121.0608,
    description: 'Communal vegetable plot utilizing organic compost from household food scraps.',
    condition: 'Active',
    details: 'Contains eggplant, tomatoes, sitao, and herbs.',
    photoUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'ast-3',
    name: 'Smart Waste Sorting Hub',
    category: 'Recycling Stations',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    lat: 14.5722,
    lng: 121.0627,
    description: '24/7 accessible segregated collection hub with electronic weight loggers.',
    condition: 'Good',
    details: 'Accepts PET plastics, aluminum cans, glass, cardboards.',
  },
  {
    id: 'ast-4',
    name: 'Solar-Powered Park Lighting',
    category: 'Solar Installations',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    lat: 14.5705,
    lng: 121.0612,
    description: '100% off-grid solar LED posts along the barangay green walkway.',
    condition: 'Operational',
  },
  {
    id: 'ast-5',
    name: 'Barangay Hall Rainwater Tank',
    category: 'Rainwater Systems',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    lat: 14.5715,
    lng: 121.0618,
    description: '5,000L rainwater storage for street washing and watering street plants.',
    condition: 'Operational',
  },
];

export const INITIAL_ALERTS: EnvironmentalAlert[] = [
  {
    id: 'alt-1',
    title: 'Flooding Alert: Pasig River Creek Spillover Risk',
    description: 'Monsoon rains caused water level rise along Lowland Creek. Please secure household waste bins to prevent floating debris clogging drainage.',
    category: 'Flooding',
    targetScope: 'City',
    targetId: 'PASIG',
    targetName: 'Pasig City',
    severity: 'High',
    createdAt: '2026-08-11T02:00:00Z',
    active: true,
    authorName: 'Pasig DRRMO & CENRO',
  },
  {
    id: 'alt-2',
    title: 'E-Waste Drive & Hazardous Battery Collection',
    description: 'Special collection box available at Barangay Hall lobby until Friday for toxic household electronic waste.',
    category: 'Hazardous Waste Incident',
    targetScope: 'Barangay',
    targetId: 'brgy-kapitolyo',
    targetName: 'Kapitolyo',
    severity: 'Low',
    createdAt: '2026-08-10T09:00:00Z',
    active: true,
    authorName: 'Brgy. Kapitolyo Eco Committee',
  },
];

export const INITIAL_BULK_PICKUPS: BulkWastePickupRequest[] = [
  {
    id: 'blk-1',
    userId: 'user-resident-1',
    userName: 'Maria Santos',
    userPhone: '+63 917 123 4567',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    wasteType: 'Bulk Cardboard',
    quantityDescription: '5 large bundles of corrugated cardboard boxes from home renovation',
    locationAddress: '12 West Capitol Drive, Brgy. Kapitolyo',
    preferredPickupDate: '2026-08-14',
    notes: 'Please call before arrival. Boxes placed near gate.',
    status: 'Scheduled',
    scheduledDate: '2026-08-14 09:00 AM',
    createdAt: '2026-08-10T11:00:00Z',
  },
];

export const INITIAL_BUSINESSES: EcoBusiness[] = [
  {
    id: 'biz-1',
    name: 'Ecofill Refillable Home & Body Hub',
    category: 'Refill Station',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    address: '45 East Capitol Drive, Brgy. Kapitolyo',
    contactPhone: '+63 918 888 7766',
    openingHours: '09:00 AM - 07:00 PM (Mon-Sat)',
    services: ['Bring Your Own Container (BYOC)', 'Liquid Detergent Refills', 'Shampoo Refills', 'Biodegradable Soaps'],
    verified: true,
    photoUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=400',
    lat: 14.5719,
    lng: 121.0622,
    rating: 4.9,
  },
  {
    id: 'biz-2',
    name: 'GreenLoop Gadget & Appliance Repair Shop',
    category: 'Repair Shop',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    address: '12 Pioneer St, Brgy. Kapitolyo',
    contactPhone: '+63 920 111 2233',
    openingHours: '10:00 AM - 06:00 PM (Mon-Fri)',
    services: ['Electronics Diagnostics', 'Smartphone Component Repair', 'Small Appliance Fixing'],
    verified: true,
    lat: 14.5710,
    lng: 121.0615,
    rating: 4.7,
  },
  {
    id: 'biz-3',
    name: 'EcoMart Zero-Waste Grocery Store',
    category: 'Zero-Waste Store',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    address: '88 Capitol Commons, Brgy. Kapitolyo',
    contactPhone: '+63 917 555 4433',
    openingHours: '08:00 AM - 08:00 PM Daily',
    services: ['Bulk Organic Grains', 'Bamboo Toothbrushes', 'Compostable Food Wraps'],
    verified: true,
    lat: 14.5730,
    lng: 121.0635,
    rating: 4.8,
  },
];

export const INITIAL_ORGANIZATIONS: PartnerOrganization[] = [
  {
    id: 'org-1',
    name: 'Kapitolyo Elementary Eco Club',
    type: 'School',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    verified: true,
    description: 'Student-led environmental advocacy group conducting campus recycling drives.',
    contactEmail: 'ecoclub@kapitolyoes.edu.ph',
    eventsCreatedCount: 5,
  },
  {
    id: 'org-2',
    name: 'Earth Savers Metro Alliance',
    type: 'NGO',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    verified: true,
    description: 'Regional non-profit focused on urban riverway restoration and plastic diversion.',
    contactEmail: 'contact@earthsavers.org.ph',
    eventsCreatedCount: 12,
  },
];

export const INITIAL_FAMILY_GROUPS: FamilyGroup[] = [
  {
    id: 'fam-1',
    familyName: 'Santos Eco Family',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    leaderUserId: 'user-resident-1',
    members: [
      { userId: 'user-resident-1', fullName: 'Maria Santos', role: 'Leader', pointsContributed: 350 },
      { userId: 'user-family-2', fullName: 'Pedro Santos', role: 'Member', pointsContributed: 200 },
      { userId: 'user-family-3', fullName: 'Liza Santos', role: 'Member', pointsContributed: 150 },
    ],
    monthlyTargetKg: 20,
    currentProgressKg: 14.2,
    totalEcoPoints: 700,
  },
];

export const INITIAL_TREES: TreeItem[] = [
  {
    id: 'tree-1',
    species: 'Narra (Pterocarpus indicus)',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    lat: 14.5714,
    lng: 121.0617,
    datePlanted: '2025-06-12',
    condition: 'Healthy',
    plantingOrg: 'Kapitolyo Youth Council',
    status: 'Active',
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'tree-2',
    species: 'Philippine Mango (Mangifera indica)',
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    lat: 14.5725,
    lng: 121.0628,
    datePlanted: '2024-03-20',
    condition: 'Mature',
    plantingOrg: 'Brgy. Kapitolyo LGU',
    status: 'Protected',
  },
];

export const INITIAL_CALENDAR_EVENTS: PersonalCalendarEvent[] = [
  {
    id: 'cal-1',
    userId: 'user-resident-1',
    title: '♻️ Recyclables & Plastics Pickup',
    date: '2026-08-12',
    time: '07:00 AM',
    type: 'Garbage Collection',
    description: 'Separate PET bottles and clean cardboards at curbside before 7:00 AM.',
    isCustom: false,
  },
  {
    id: 'cal-2',
    userId: 'user-resident-1',
    title: '🌳 Riverbank Tree Planting Event',
    date: '2026-08-15',
    time: '06:00 AM',
    type: 'Cleanup Event',
    description: 'Bring water bottle and gardening gloves.',
    isCustom: false,
  },
  {
    id: 'cal-3',
    userId: 'user-resident-1',
    title: '📦 Scheduled Bulk Pickup',
    date: '2026-08-14',
    time: '09:00 AM',
    type: 'Personal Reminder',
    description: 'Cardboard boxes pickup by barangay truck.',
    isCustom: true,
  },
];

export const INITIAL_BARANGAY_IMPROVEMENTS: BarangayImprovement[] = [
  {
    barangayId: 'brgy-kapitolyo',
    barangayName: 'Kapitolyo',
    cityName: 'Pasig City',
    previousScore: 86.6,
    currentScore: 90.0,
    scoreImprovement: 3.4,
    rankImprovement: 2,
    timeframe: 'Monthly',
  },
  {
    barangayId: 'brgy-san-antonio',
    barangayName: 'San Antonio',
    cityName: 'Pasig City',
    previousScore: 82.1,
    currentScore: 87.2,
    scoreImprovement: 5.1,
    rankImprovement: 4,
    timeframe: 'Monthly',
  },
  {
    barangayId: 'brgy-loyola-heights',
    barangayName: 'Loyola Heights',
    cityName: 'Quezon City',
    previousScore: 81.0,
    currentScore: 85.8,
    scoreImprovement: 4.8,
    rankImprovement: 3,
    timeframe: 'Monthly',
  },
];



